# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Node.js version
build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"

# Build documentation using JSDoc
jsdoc:
  # The path to the JavaScript source files
  source:
    - ./client/scripts/main.mjs
    - ./server.js
    - ./dbConnection.js
  # The output directory for the generated documentation
  output: docs
  # Additional JSDoc configuration options
  config:
    # The path to the JSDoc configuration file (if any)
    #configFile: jsdoc.conf.json
    # Other JSDoc options
    #templateDir: node_modules/jsdoc-templates
    #template: minami

# Optional: Specify the Python requirements if you need to install any Python packages
# python:
#   install:
#     - requirements: docs/requirements.txt

# Optional: Build your docs in additional formats such as PDF and ePub
# formats:
#   - pdf
#   - epub
