--Up

-- user table
CREATE TABLE USER(
USER_ID SERIAL PRIMARY KEY,
USER_FNAME VARCHAR(35) NOT NULL,
USER_LNAME VARCHAR(35) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ACCOUNT_CREATION_TIMESTAMP TIMESTAMP
);

-- recipe table
CREATE TABLE RECIPE(
RECIPE_ID SERIAL PRIMARY KEY,
RECIPE_NAME VARCHAR(50) NOT NULL,
COOKING_STEP VARCHAR(100) NOT NULL,
CUISINE_TYPE VARCHAR(100) NOT NULL,
PREPARATION_TIME INT NOT NULL,
NUTRITION_INFO VARCHAR(100) NOT NULL
);

-- saved_recipe table 
CREATE TABLE SAVED_RECIPE(
USER_ID INT NOT NULL,
RECIPE_ID INT NOT NULL,
DATE_SAVED TIMESTAMP,
PRIMARY KEY (USER_ID, RECIPE_ID),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);

-- ingredient table
CREATE TABLE INGREDIENT(
INGREDIENT_ID SERIAL PRIMARY KEY,
INGREDIENT_NAME VARCHAR(35) NOT NULL
);

-- recipe_ingredient table
CREATE TABLE SAVED_RECIPE(
USER_ID INT NOT NULL,
RECIPE_ID INT NOT NULL,
PRIMARY KEY (USER_ID, RECIPE_ID),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);