--Up

-- user table
CREATE TABLE USER(
USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
USER_FNAME VARCHAR(35) NOT NULL,
USER_LNAME VARCHAR(35) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ACCOUNT_CREATION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- recipe table
CREATE TABLE RECIPE(
RECIPE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
RECIPE_NAME VARCHAR(50) NOT NULL,
COOKING_STEP TEXT NOT NULL,
CUISINE_TYPE VARCHAR(20) NOT NULL,
PREPARATION_TIME INTEGER NOT NULL,
NUTRITIONAL_INFO TEXT NOT NULL
);

-- saved_recipe table 
CREATE TABLE SAVED_RECIPE(
USER_ID INTEGER NOT NULL,
RECIPE_ID INTEGER NOT NULL,
DATE_SAVED DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (USER_ID, RECIPE_ID),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);

-- ingredient table
CREATE TABLE INGREDIENT(
INGREDIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
INGREDIENT_NAME VARCHAR(50) NOT NULL
);

-- recipe_ingredient table
CREATE TABLE RECIPE_INGREDIENT(
INGREDIENT_ID INTEGER NOT NULL,
RECIPE_ID INTEGER NOT NULL,
PRIMARY KEY (INGREDIENT_ID, RECIPE_ID),
FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);

-- -- INSERT INTO recipe table
-- INSERT INTO RECIPE (RECIPE_NAME, COOKING_STEP, CUISINE_TYPE, PREPARATION_TIME, NUTRITIONAL_INFO) VALUES 
-- ('Spaghetti Bolognese', '1. Cook spaghetti according to package instructions. 2. In a large skillet, heat olive oil over medium heat. 3. Add ground beef and cook until browned. 4. Add onions, garlic, and carrots. Cook until vegetables are tender. 5. Stir in tomato paste, diced tomatoes, and beef broth. 6. Simmer for 20 minutes. 7. Serve sauce over cooked spaghetti.', 'Italian', 30, 'Calories: 450, Fat: 15g, Carbs: 50g, Protein: 25g');

-- -- INSERT INTO ingredient table
-- INSERT INTO INGREDIENT (INGREDIENT_NAME) VALUES
-- ('Spaghetti'),
-- ('Olive Oil'),
-- ('Ground Beef'),
-- ('Onions'),
-- ('Garlic'),
-- ('Garlic'),
-- ('Tomato Paste'),
-- ('Diced Tomatoes'),
-- ('Beef Broth');

-- INSERT INTO recipe table
INSERT INTO RECIPE (RECIPE_NAME, COOKING_STEP, CUISINE_TYPE, PREPARATION_TIME, NUTRITIONAL_INFO) VALUES 
('Spaghetti Bolognese', '1. Cook spaghetti according to package instructions. 2. In a large skillet, heat olive oil over medium heat. 3. Add ground beef and cook until browned. 4. Add onions, garlic, and carrots. Cook until vegetables are tender. 5. Stir in tomato paste, diced tomatoes, and beef broth. 6. Simmer for 20 minutes. 7. Serve sauce over cooked spaghetti.', 'Italian', 30, 'Calories: 450, Fat: 15g, Carbs: 50g, Protein: 25g'),
('Jacket Potato with Beans or Tuna', '1. Preheat your oven to 200°C (400°F). 2. Wash the baking potato thoroughly under running water and pat dry with a kitchen towel. 3. Prick the potato several times with a fork to allow steam to escape while cooking. 4. Optionally, for a quicker cooking process, place the potato in the microwave and heat on high for 1 minute. 5. Transfer the partially cooked potato to the preheated oven and bake for approximately 30 minutes, or until the skin is crispy and the flesh is soft inside. 6. While the potato is baking, prepare your choice of filling: a. For beans: Heat up canned baked beans in a microwave-safe dish until hot. b. For tuna: Mix canned tuna with mayonnaise according to your preference. 7. Once the potato is cooked through and your filling is ready, remove the potato from the oven. 8. Carefully cut open the potato lengthwise, creating a slit down the middle. 9. Use a fork to lightly fluff up the flesh inside the potato. 10. Fill the potato with your chosen topping, either the heated beans or the tuna mixture. 11. Serve immediately, optionally garnishing with additional toppings like grated cheese, chopped chives, or a dollop of sour cream.', 'Western', 35,  '1. Calories: 200-400 kcal 2. Fat: 5-10 grams 3. Carbs: 30-50 grams 4. Protein: 10-20 grams'),
('Cheese and ham omelette', '1. Gently beat the eggs together in a mixing bowl and season, to taste, with salt and pepper. 2. Heat the butter in a frying pan until foaming. Pour in the eggs and cook for a few seconds, until the bottom of the omelette is lightly set. Push the set parts of the omelette into the uncooked centre of the omelette. Cook again, until the omelette has set further, then push those set parts into the centre of the omelette again. Repeat the process until the eggs have just set but the omelette is still soft in the centre. 3. Put the cheese and three-quarters of the ham in the centre of the omelette and cook until the cheese has melted. 4. Increase the heat to high and cook the omelette for a further 30 seconds, or until it browns on the bottom. 5. Fold the omelette in half, then remove the pan from the heat and tilt it slightly to move the omelette to the edge of the pan. Slide the omelette onto a serving plate, then shape it into a neat roll. Sprinkle over the remaining ham.', 'Western', 30, '1. Calories: 492 kcal 2. Protein: 39 grams 3. Carbohydrates: 0 grams 4. Sugars: 0 grams 5. Fat: 37 grams 6. Saturated Fat: 17 gram 7. Fiber: 0 grams 8. Salt: 3.3 grams')
('Vegetarian chili', '1. Heat oil in a Dutch oven or a large stockpot over medium heat. Throw in onion, bell pepper, carrots, and celery and season with salt and pepper. Stir and cook those bad boys for 7–10 minutes, until they’re soft. 2. Spice time! Sling in garlic, chili powder, cumin, paprika, and oregano (extra points for doing it from the other side of the kitchen and shouting “KOBE!”). Let everything sizzle for 1 minute, until it smells like a good-ass chili. 3. Mix in every bean at your disposal and the diced tomatoes and their juice. It’s also time for the broth and bay leaf. Stir everything together and simmer all that business for 30 minutes, keeping an eye on the heat to keep a steady simmer going. 4. Take the masterpiece off the heat and get rid of the bay leaf. To make the texture Oscar-worthy, move 1 1/2 cups of chili to a blender, whirl it until it’s smoother than Ryan Gosling dressed as Prince, and return it to its friends in the main pot. (If you don’t have a blender, mash the chili with a potato masher.) 5. Once the texture is spot-on, stir in the cilantro and add salt and sherry vinegar to taste.', 'Southwestern(Tex-Mex)', 40, '1. Calories: 200-300 kcal 2. Protein: 10-15 grams 3. Carbohydrates: 20-30 grams 4. Fiber: 5-10 grams 5. Fat: 5-10 grams 6. Sugars: < 5 grams 7. Sodium: < 1000 mg'),
('Summer traybake chicken', '1. Put the chicken breasts in a large, shallow roasting tray. 2. Drizzle the chicken breasts with olive oil. 3. Grill the chicken for 10 minutes. 4. After 10 minutes, add the cherry tomatoes to the roasting tray. 5. Continue grilling for another 5 minutes or until the chicken is cooked through. 6. Once cooked, drizzle pesto over the top of the chicken and serve.', 'Western or Modern European', 15, '1. Calories: 0 kcal 2. Fat: 0g 3. Saturates: 0g 4. Carbohydrates: 0g 5. Sugars: 0g 6. Fiber: 0g 7. Protein: 0g 8. Low in Salt: 0g'),
('Linguine With Tomato Sauce', '1. Coarsely chop the tomatoes, reserving the juices. Heat the oil in a large saucepan over medium heat. Add the garlic and cook until fragrant, about 30 seconds. 2. Add the tomatoes and their juices, 1 ½ teaspoons salt, and ¼ teaspoon pepper. Simmer, stirring occasionally, until the tomatoes break down and the sauce thickens, 45 to 50 minutes. 3. When the sauce has 20 minutes left to cook, cook the pasta according to the package directions. Drain the pasta and return it to the pot. Add the sauce and basil and toss to combine.', 'Italian', 60, '1. Calories: 433 kcal 2. Fat: 12 grams 3. Carbohydrates: 71 grams'),
('Stuffed peppers with rice', '1. Use a small knife to cut the top out of 4 red peppers, then scoop out the seeds. 2. Sit the peppers on a plate, cut-side up, and cook in the microwave on high for 5-6 mins until they have wilted and softened. 3. While the peppers are cooking, mix: a. Two 250g pouches of cooked tomato rice b. 2 tbsp pesto c. A handful of chopped pitted black olives d. 140g of sliced goat''s cheese. 4. Scoop the rice, pesto, olives, and goat''s cheese mix into the peppers. 5. Top with the remaining 60g sliced goat’s cheese. 6. Continue to cook for 8-10 mins.', 'Mediterranean or modern European', 15, 'Calories: 387 kcal Fat: 17 grams Saturates: 7 grams Carbohydrates: 46 grams Sugars: 14 grams Fiber: 4 grams Protein: 15 grams Salt: 2.1 grams'),
('Easy chicken fajitas', '1. Heat oven to 200°C/180°C fan/gas 6 and wrap 8 medium tortillas in foil. 2. Mix 1 heaped tbsp smoked paprika, 1 tbsp ground coriander, a pinch of ground cumin, 2 crushed garlic cloves, 4 tbsp olive oil, the juice of 1 lime, and 4-5 drops Tabasco together in a bowl with a big pinch each of salt and pepper. 3. Stir 2 finely sliced chicken breasts, 1 finely sliced red onion, 1 sliced red pepper, and 1 finely sliced red chilli (if using) into the marinade.', 'Mexican', 25, 'Calories: 494 kcal Fat: 20 grams Saturates: 4 grams Carbohydrates: 50 grams Low in Sugars: 9 grams Fiber: 8 grams Protein: 25 grams Salt: 1.49 grams'),
('Roll-your-own fajitas', '1. Mix the cumin, coriander, and cayenne with some salt and pepper, then set aside. Heat half the oil in a frying pan, then throw in the onion, peppers, and half the spice mix. Cook for about 3 mins. Tip the vegetables into a bowl. 2. Place the pan back on the heat with the remaining oil, then fry the steak and remaining spice mix together for 4 mins until cooked through. Tip the steak into a separate bowl, garnishing with coriander. Heat the wraps. Bring everything to the table and let everyone help themselves.', 'Mexican', 25, 'Calories: 495 kcal Fat: 23 grams Saturates: 8 grams Carbohydrates: 45 grams Sugars: 10 grams Fiber: 4 grams Protein: 30 grams Salt: 1.74 grams'),
('Gnocchi & tomato bake', '1. Heat grill to high. Heat 1 tbsp olive oil in a large frying pan, then soften 1 chopped onion and 1 finely chopped red pepper for 5 mins. 2. Stir in 1 crushed garlic clove, fry for 1 min, tip in 400g chopped tomatoes and 500g gnocchi, then bring to a simmer. 3. Bubble for 10-15 mins, stirring occasionally, until the gnocchi is soft and the sauce has thickened. 4. Season, stir through a handful of torn basil leaves, then transfer to a large ovenproof dish.', 'Italian', 30, 'Calories: 285 kcal Low in Fat: 7 grams Saturates: 3 grams Carbohydrates: 50 grams Sugars: 8 grams Fiber: 4 grams Protein: 10 grams Salt: 1.64 grams'),
('Chicken, squash & pesto lasagne', '1. Heat the oil in a large casserole dish. Add the onions and cook until softened, then add the garlic and cook for a few mins more. Push the onions and garlic to the edge of the pan, add the chicken breasts and cook for a few mins each side to brown. Sprinkle over the flour and stir it into the onion mixture. Tip in the stock and season. Cover and simmer for 10 mins – or until the chicken is cooked through. Using 2 forks, shred the chicken into bite-sized chunks. Add half the mascarpone and the pesto, stirring until the mascarpone has melted into the sauce, bubble for a few mins to thicken a little, then remove from the heat and stir in the basil. 2. Meanwhile, place the squash in a large bowl with 2 tbsp of water, cover with cling film and microwave on High for 12-15 mins, until really soft. Season the squash with a little of the nutmeg and some salt and pepper, and mash lightly with a fork. 3. Heat oven to 180°C/160°C fan/gas 4. Spoon half the chicken mixture into the bottom of a 20 x 30cm ovenproof dish. Cover with 4 lasagne sheets, then the butternut squash and half the Parmesan. Top with another 4 lasagne sheets, the remaining chicken mixture, then a final layer of lasagne. Mix enough milk into the remaining mascarpone to make a smooth sauce – you need to aim for a consistency similar to white sauce. Season with remaining nutmeg, salt and pepper, then pour over the lasagne. Scatter over the remaining Parmesan and the pine nuts. Bake for 40 mins until piping hot in the centre and crunchy and golden on top. Scatter with a few extra basil leaves before serving.', 'Italian', 85, 'Calories: 692 kcal Fat: 50 grams Saturates: 23 grams Carbohydrates: 30 grams Sugars: 9 grams Fiber: 4 grams Protein: 31 grams Salt: 1.3 grams'),
('Speedy sausage stroganoff tagliatelle', '1. Heat the butter and oil in a frying pan over a medium-high heat until foaming. Squeeze large chunks of the sausagemeat out of the skins and into the pan. Cook for 5-8 mins or until golden brown. Add the mushrooms and cook for a further 5 mins until starting to turn brown. Stir through the paprika and cook for 1 min before stirring in the soured cream, mustard and stock. Bring to a simmer and season to taste. 2. Meanwhile, cook the pasta in a large pan of salted water according to pack instructions, then add to the sauce with half the parsley. Serve in deep bowls with the remaining parsley sprinkled on top.', 'Italian or Russian', 20, 'Calories: 826 kcal Fat: 42 grams Saturates: 20 grams Carbohydrates: 80 grams Sugars: 7 grams Fiber: 10 grams Protein: 27 grams Salt: 1.2 grams'),
('Caponata pasta', '1. Heat the oil in a large pan and cook the onion for 8-10 mins until starting to caramelise (or for longer if you have time – the sweeter the better). Add the garlic for the final 2 mins of cooking time. 2. Tip in the mixed veg, tomatoes, capers, and raisins. Season well and simmer, uncovered, for 10 mins, or until you have a rich sauce. 3. Meanwhile, boil the kettle. Pour the kettleful of water into a large pan with a little salt and bring back to the boil. Add the pasta and cook until tender with a little bite, then drain, reserving some of the pasta water. Tip the pasta into the sauce, adding a splash of pasta water if it needs loosening. Scatter with the basil leaves and parmesan, if you like, and serve straight from the pan.', 'Italian', 20, 'Calories: 542 kcal Fat: 14 grams Saturates: 2 grams Carbohydrates: 85 grams Sugars: 21 grams Fiber: 9 grams Protein: 14 grams Salt: 0.5 grams'),
('Big-batch bolognese', '1. Heat the oil in a very large saucepan. Gently cook the bacon, onions, carrots, and celery for 20 mins until golden. Add the garlic, herbs, bay, and mushrooms, then cook for 2 mins more. 2. Heat a large frying pan until really hot. Crumble in just enough mince to cover the pan, cook until brown, then tip in with the veg. Continue to fry the mince in batches until used up. Tip the tomatoes and purée in with the mince and veg. Rinse the cans out with the red wine, if you have some, or with a little water, then add to the pan with the vinegar and sugar. Season generously and bring to a simmer. Simmer slowly for 1 hr until thick and saucy and the mince is tender. Serve with pasta and parmesan.', 'Italian', 115, 'Calories: 295 kcal Fat: 12 grams Saturates: 4 grams Carbohydrates: 13 grams Sugars: 11 grams Fiber: 4 grams High in Protein: 34 grams Low in Salt: 0.87 grams'),
('Easy chicken curry', '1. Heat the oil in a flameproof casserole dish or large frying pan over a medium heat. Add the onion and a generous pinch of salt and fry for 8-10 mins, or until the onion has turned golden brown and sticky. Add the garlic and ginger, cooking for a further minute. 2. Chop the chicken into chunky 3cm pieces, add to the pan and fry for 5 mins before stirring through the spice paste and tomatoes, along with 250ml water. Bring to the boil, lower to a simmer and cook on a gentle heat uncovered for 25-30 mins or until rich and slightly reduced. Stir though the yogurt, coriander and ground almonds, season and serve with warm naan or fluffy basmati rice.', 'Indian', 50, 'Calories: 354 kcal Fat: 23 grams Saturates: 4 grams Carbohydrates: 10 grams Sugars: 8 grams Fiber: 3 grams Protein: 24 grams Salt: 0.6 grams'),
('Roasted aubergine & tomato curry', '1. Heat oven to 200°C/180°C fan/gas 6. Toss the aubergines in a roasting tin with 2 tbsp olive oil, season well, and spread out. Roast for 20 mins or until dark golden and soft. 2. Heat the remaining oil in an ovenproof pan or flameproof casserole dish and cook the onions over a medium heat for 5-6 mins until softening. Stir in the garlic and spices, for a few mins until the spices release their aromas. 3. Tip in the tomatoes, coconut milk, and roasted aubergines, and bring to a gentle simmer. Simmer for 20-25 mins, removing the lid for the final 5 mins to thicken the sauce. Add a little seasoning if you like, and a pinch of sugar if it needs it. Stir through most of the coriander. Serve over rice or with chapatis, scattering with the remaining coriander.', 'Indian', 60, 'Calories: 331 kcal Fat: 26 grams Saturates: 16 grams Carbohydrates: 15 grams Sugars: 12 grams Fiber: 7 grams Protein: 5 grams Salt: 0 grams'),
('Green curry paste', '1. Heat a dry frying pan and add the coriander and cumin seeds, mace, and nutmeg. Roast until they begin to color and release their aromas. Remove from the heat, then grind to a powder in a spice mill or blender. 2. Put the garlic in a blender or pound using a pestle and mortar, then add the shallots, coriander roots, chilies, galangal, lemongrass, and 2 tsp salt. Finally, add the lime leaves, shrimp paste, basil, and the ground spices, then whizz or pound until you have a smooth paste.', 'Thai', 20, 'Calories: 18 kcal Fat: 1 gram Saturates: 0 grams Carbohydrates: 2 grams Sugars: 1 gram Fiber: 0 grams Protein: 2 grams Low in Salt: 1.2 grams'),
('Sticky Chinese five-spice chicken traybake', '1. Heat oven to 200°C/180°C fan/gas 6. Arrange the chicken thighs in a large roasting tin and slash the skin 2-3 times on each thigh. Mix together the hoisin, sesame oil, honey, five-spice, ginger, garlic, and some seasoning. Pour over the chicken and toss to coat – you could now marinate the chicken for 2 hrs, or overnight if you have time. Roast, skin-side up, for 35 mins, basting at least once. 2. Stir through the cashew nuts and sprinkle the spring onions over the chicken. Return to the oven for 5 mins, then serve with brown rice.', 'Chinese', 50, 'Calories: 450 kcal Fat: 27 grams Saturates: 7 grams Carbohydrates: 19 grams Sugars: 14 grams Fiber: 2 grams Protein: 32 grams Salt: 1 gram'),
('Halloumi traybake', '1. Heat oven to 160C/140C fan/gas 3. Put the potatoes in a large roasting tin with the onion. Pour over 2 tbsp olive oil and roast in the oven for about 30 mins. 2. Add the chickpeas, pepper, romanesco, tomatoes and garlic. Drizzle with 2 tbsp oil, then roast for a further 20-25 mins until everything is cooked and browning nicely. Toss together briefly and put the halloumi slices on top. Put it under the grill for 5-10 mins, or until the cheese is melting and browning (keep an eye on it). Scatter over the basil leaves to serve.', 'Mediterranean', 75, 'Calories: 564 kcal Fat: 24g Saturated fat: 8g Carbohydrates: 53g Sugars: 15g Fiber: 12g Protein: 28g Salt: 1.6g'),
('5-a-day chicken with kale & pistachio pesto', '1. Heat oven to 200C/180C fan/gas 6. Put all the veg for the bake except the garlic in a large bowl and add 1 tbsp olive oil, then carefully turn everything over with your hands so the oil adds a very thin coating. Lightly oil the tray as well if you are worried about things sticking. 2. Arrange the veg in piles on the tray, or scatter it all over if you prefer. Add the garlic halves and the chicken, sitting the chicken on top of the veg. Season well and bake for 40 mins then, if the chicken skin is still pale, either turn the oven up or turn it onto the grill setting, and cook or grill until it is nicely browned. 3. Meanwhile, make the pesto. Whizz the kale, garlic and pistachios until everything is finely chopped. Add the parmesan, lemon juice and olive oil and whizz again. Add a splash of water to loosen. Any left over will keep in a jar for up to three days in the fridge. Serve the chicken and veg with the pesto spooned over.', 'Mediterranean', 65, 'Calories: 698 kcal Fat: 40g Saturated fat: 9g Carbohydrates: 34g Sugars: 18g Fiber: 16g Protein: 42g Salt: 0.7g'),
('Prosciutto Pasta with Peas and Parmesan Cheese', '1. Cook pasta in boiling water until al dente. During the last 5-7 minutes of cooking, add frozen peas and continue boiling both the pasta and frozen peas for 5-7 more minutes. Drain. Reserve ½ cup pasta water. 2. Tear prosciutto into smaller pieces. 3. In a large skillet, heat 2 tablespoons butter on medium heat. Add the torn prosciutto and stir to coat it with butter, for about 1 minute. Add black pepper. Add another 2 tablespoons of butter and stir until melted. 4. To the skillet with butter and prosciutto add drained cooked pasta with peas. Sprinkle ¾ cup shredded Parmesan cheese evenly over pasta. Stir everything together on medium heat until the cheese melts. If needed, add a small amount of pasta water (about ¼ cup) - but you might not need to. Season with salt, if needed. Serve immediately, topped with the remaining ¼ cup shredded Parmesan cheese', 'Italian', 30, 'Calories: 527 kcal fat: 27 g carbs: 48 g protein: 21 g cholesterol: 61 mg sodium: 719 mg fiber: 3 g saturated fat: 14 g sugar: 3g'),
('Minestrone in minutes', '1. Bring the stock to the boil with the tomatoes, then add the spaghetti and cook for 6 mins or until done. A few minutes before the pasta is ready, add the vegetables and bring back to the boil. Simmer for 2 mins until everything is cooked. 2. Serve in bowls drizzled with pesto and oil, sprinkled with parmesan.', 'Italian', 10, 'Calories: 162 kcal Fat: 2g Saturated fat: 0g Carbohydrates: 30g Sugars: 8g Fiber: 6g Protein: 8g Salt: 0.54g'),
('Pistou soup', '1. Heat the oil in a large pan and sweat the onion, carrots, celery, fennel, turnip, celeriac, and parsnip for 5-10 mins. Pour over 1.6 litres of boiling water, season and simmer for 10-15 mins, until the vegetables are tender. At the last moment add the peas and the beans and cook for a further 1 min. Taste and season with salt and pepper as necessary. 2. Meanwhile, make the pesto sauce. Blanch the basil leaves in boiling water for 5 secs, then remove and cool under cold running water. Pat dry and purée all the ingredients in a liquidiser. Taste and season, then reserve. Keep in the fridge until required. When ready to serve, pour the soup into a large, warmed tureen, top with some of the pesto sauce and serve to your guests. Place Parmesan and croûtons on the table so guests may help themselves.', 'French', 30, 'Calories: 201 kcal Fat: 15g Saturated fat: 2g Carbohydrates: 13g Sugars: 7g Fiber: 7g Protein: 4g Salt: 0.15g'),
('Rice and peas','1. Soak the red kidney beans overnight. 2. Boil the red kidney beans in boiling water until al dente. 3. Add the scallion, garlic, pimento, and salt to the boiling mixture. 4. After about 2-3 minutes, add the washed Tilda rice and coconut milk and leave to boil for 5 minutes. 5. Add the rest of the sauce ingredients and give it a good mix and keep aside. 6. After 5 minutes, lower the fire and steam for 15 minutes until the rice is perfectly cooked.', 'Jamaica', 30, 'Calories: 299 Fat: 7.83g Carbohydrates: 49.58g Protein: 6.22g'),
('Nigerian fried rice', '1. Cook your Tilda rice according to the packet instructions, using a ratio of 1 part rice to 2 parts water. Add the stock cube to the water and stir to dissolve. Cover the pan and bring to a boil. Once boiling, do not remove the lid. Reduce the heat to low and cook for 5 minutes. Turn off the heat without lifting the lid and let the rice rest for a few minutes in the steam. The rice grains should separate nicely and not be too sticky. 2. In a pan over medium heat, heat the oil and add the onions and carrot. Simmer to soften for 2-3 minutes. Add the prawns and curry powder, mushrooms, green pepper, tomatoes, peas, and sweet corn. Simmer for a further 3-4 minutes. 3. Transfer the cooked rice into the pan with the prawns and vegetables. Add the whole Scotch bonnet and thyme leaves (save some for garnish) and cook over low heat for 4-5 minutes. Add salt to taste. 4. To serve, spoon the rice into a warm bowl and top with thyme leaves for garnish.', 'Nigeria', 60, 'Calories: 311'),
('Caribbean spicy rice', '1. Add onions, garlic, Scotch bonnet, bell peppers, and frozen peas to a pan with some olive oil. Cook down until soft. 2. Add turmeric to the pan, then pour in coconut milk and water to create a sauce. 3. Add washed rice to the sauce and mix it in. 4. Add butter and seasonings to the rice mixture. 5. Cook for 25 minutes on low heat until the rice is cooked.', 'Caribbean', 30, 'Calories: 250-400'),
('Nigerian lamb curry', '1. Season the lamb pieces by placing them in a bowl with EVOO (extra virgin olive oil), garlic, spring onions, and chicken stock cubes. Rub the seasoning into the skin. Leave for 1-2 hours or overnight covered in the fridge. 2. Take the lamb out of the fridge and allow it to reach room temperature. 3. Add some olive oil to a pan and sear the lamb pieces on medium-high heat for ten minutes, turning over until all areas are browned. Remove the lamb from the pan and set it aside to rest. 4. Finely chop the onions, bell peppers, tomatoes, Scotch bonnet, spring onions, garlic, and coriander. 5. Add some more olive oil to the pan and sauté the chopped mixture. 6. Add the Knorr chicken stock pot, stir, and allow it to cook for 3 minutes. 7. Pour in the coconut milk and cream, then stir and allow to simmer for five minutes. 8. Add the seasonings (curry, ground mixed spice, and salt to taste). 9. Add the lamb pieces back into the pan, ensuring they are coated in the sauce. Turn the heat down to medium and leave to cook for an hour. 10. Add the cubed white sweet potatoes and craisins, then leave for 40 minutes on medium heat. 11. Serve with boiled rice, garnished with fresh coriander, red chili, and pomegranate. Enjoy!', 'Nigeria', 90, 'Calories: 400-600'),
('Nigerian banga rice', '1. Chop the onions and cow skin into small pieces. Discard the head of the smoked catfish and break it into smaller chunks. Do the same for the dried shrimps. 2. Using a food processor, pulse the bell pepper, sweet pepper, and Scotch bonnet until they are finely chopped but still visible. 3. Soak the rice in hot water for 5 minutes, then wash and rinse out the water to remove any excess starch. 4. Soak the dried scent leaves in hot water for 5 minutes, then discard the water. 5. Add Sunflower oil to a heated pan and pour in the onions. Allow to simmer for a few seconds, followed by the sweet pepper, Scotch bonnet, and red bell pepper blend. Cook for about 2 minutes. 6. Add the banga palm nut soup, cow skin, smoked catfish, half of the crayfish, half of the dried shrimp, Maggi, salt, banga spice, and allow to cook for 5 minutes. 7. Add the Tilda Easy Cook Long grain rice and 200g of water, then cook for another 15 minutes. 8. Using a wooden spoon, stir the rice and add the remaining crayfish, dried shrimp, and scent leaves. 9. Taste and adjust seasoning, adding additional Maggi or salt if needed. Reduce the heat and cook for an additional 10 minutes. 10. Enjoy your meal!', 'Nigeria', 60, 'Calories: 300-400'),
('African vegetable pilau', '1. Sauté carrots and onions until onions have lightly browned. 2. Add spices and cook for at least another 5 minutes. 3. Add washed rice followed by water, season with salt to taste, and stir in star anise and bay leaf. 4. Bring pot to a boil, then reduce the heat and cover with a lid. Leave covered and cook on low heat for 20 minutes. 5. Remove lid and fluff rice before serving. Perfect every time!', 'African', 30, 'Calories: 281 Total Fat: 4.4g Saturated Fat: 0.4g Cholesterol: 0mg Sodium: 1014mg Total Carbohydrates: 54g Dietary Fiber: 1g Sugars: 1.9g Protein: 5.4g Vitamin D: 0.1mcg Calcium: 13mg Iron: 0.7mg Potassium: 203.6mg'),
('Seafood jollof', '1. In a food processor, add 2 onions, tomatoes, garlic, Scotch bonnet chili, and bell pepper. Pulse until smooth. 2. Add olive oil to a heated pan and pour in the blended tomatoes and onions, followed by the seasonings: bay leaves, mixed herbs, fresh thyme, black pepper, curry powder, and salt to taste. 3. Simmer for 15 minutes until the sauce has reduced and is deep red in color. 4. Add the rice and 2 cups of water. Bring to a boil, then reduce the heat to low and cover the pot with a lid. Simmer for another 30 minutes, until the rice is cooked through and the liquid is absorbed. 5. For the seafood, in a separate pan, add olive oil, then begin adding the seafood mix one at a time. 6. Season all the seafood with black pepper, mixed herbs, sea salt, garlic granules, and cayenne pepper. 7. Lightly stir-fry for 3-4 minutes until cooked. 8. Once the rice has cooked, add the seafood over the rice and serve.', 'West African', 60, 'Calories: 376 Total Fat: 17g Saturated Fat: 5.2g Cholesterol: 45mg Sodium: 665mg Total Carbohydrates: 36g Dietary Fiber: 0.4g Sugars: 1.9g Protein: 17g Vitamin D: 0.4mcg Calcium: 25mg Iron: 2mg Potassium: 384.9mg'),
('Senegalese rice with grilled sea bass', '1. Wash the rice, drain, and set aside. Pour the oil into a heavy-bottomed saucepan and place over medium heat. Add the onions with a pinch of salt and cook for 7 minutes until softened. Stir in the garlic until fragrant. 2. Add the crushed tomatoes and purée, stir, and cover to cook for 5 minutes. Now pour in the stock and add the tamarind paste. Bring to a steady simmer and tuck the vegetables into the sauce. Pierce the scotch bonnet and add it to the sauce. Season with thyme, 1 tsp of fine sea salt, ½ tsp black pepper, and cover to cook. Remove the softer vegetables first; aubergines after 15 minutes, cabbage and carrots after 20 – 25 minutes. Remove', 'Senegal', 90, 'Calories:300-400, Protein:20-25 grams, Carbohydrates:30-40 grams, Fat:10-15 grams, Fiber:2-4 grams'),
('Peppered chicken', '1. Preheat oven to 180°C/356°F. 2. Coat the chicken with 2 tbsp oil, and massage in the curry powder, thyme, and 1 tsp of salt. 3. Grill in the oven for 20 mins until the skin is crisp and just cooked through. 4. Blend the bell peppers, plum tomatoes, scotch bonnet, 1 red onion, ginger, and garlic to a smooth paste. 5. Slice the remaining 2 red onions, slice up the green pepper into small thin strips, and finely slice the spring onions. 6. In a large pot, add in 3 tbsp of oil and add sliced red onion, cook for 5 mins until lightly browned. 7. Add the tomato purée and cook for 5-6 mins until deeply browned (a very important step, make sure it is a dark red so that it loses the bitterness). 8. Add the 1 tsp curry powder, 1 tsp thyme, and cook for 1 min. 9. Pour in the blended pepper sauce and cook for 10-15 mins until it reduces by almost half. 10. Meanwhile, rinse your Tilda Basmati Rice in cold water until the water runs clear. Pop in a pan with 500ml of cold water to bring to a simmer. Cook for 10 - 12 mins until the rice is tender and then fluff up with a fork. 11. Then add in 250ml water and add in the stock cube, sugar, and 1 tsp salt. Add the cooked chicken and mix thoroughly. 12. Leave to cook uncovered for 5-8 mins, ensuring the chicken is warmed through. 13. Whilst the chicken is cooking, sauté the green peppers until slightly charred and softened for 5 mins. 14. Serve with a sprinkling of the peppers, spring onions, and the cooked rice.', 'Nigeria', 90, 'Calories:230'),
('Coconut rice with grilled chicken suya', '1. Prepare a broth for the chicken and coconut rice by heating a tablespoon of coconut oil in a wide saucepan. Add the sliced onion and cook over a medium heat until softened, then add the garlic and ginger and cook for 2 minutes. 2. Lightly toast the whole seeds in a hot dry frying pan for a minute or until darker in color, then crush with a pestle and mortar and add to the onions. Add the curry powder and stir. 3. Throw in the bay leaf, coconut milk, crushed whole uda pod, and sea salt. Stir well, bring the broth to the boil and add the chicken thighs. Reduce heat to low, cover, and poach for 5 minutes. 4. Remove the uda pod and poached chicken from the broth with a slotted spoon and place in a colander to drain. 5. For the coconut rice, rinse the rice, drain well, and add to the coconut broth. Cook tightly covered over medium heat for 5 minutes. Add the chopped carrots and green beans, then cook for a further 5 minutes. 6. Check the rice for doneness and, if needed, add 100–200ml of water at a time. Continue to cook until the rice is tender. Once cooked, sprinkle with chopped spring onions and fluff the rice with a fork. 7. For the suya, dry roast the peanuts in a hot frying pan until golden then crush into a fine powder using a pestle and mortar or food processor. Transfer to a muslin cloth and squeeze out as much oil as possible, until you are left with a cakey peanut residue. 8. Crush the uda pods as finely as possible, separating and discarding the coarse bark. Mix the peanuts and crushed uda pods with the garlic, ginger, and chili powder, then season with sea salt. Save a tablespoon or two of the suya spices for garnish, and use the rest to coat both sides of the poached chicken thighs.9. Heat a grill or griddle pan until smoking hot. Brush the chicken on both sides with coconut oil and grill for 5 minutes on each side or until cooked through. Once cooked, remove the chicken from the grill and leave to rest. Place the beef tomatoes and onions on the grill until charred. 10. Slice the grilled chicken into thin strips and serve with the coconut rice, char-grilled onions and tomatoes and a sprinkling of the reserved suya spices.', 'Nigeria', 60, ' Calories:500-800 calories, Protein:20-40 grams, Fat:20-40 grams, Carbohydrates:50-100 grams, Fiber:5-10 grams'),
('Jollof rice with kelewele', '1. Begin by preparing the kelewele. Cut about 1.5 cm off the tips of the plantain. Make a lengthways incision into the skin and peel the plantain. Halve lengthways, then slice into 1.5–2cm chips. 2. Prepare a marinade by blending all the remaining kelewele ingredients, reserving some of the thyme sprigs for a fresh garnish. Add the plantain chips to the marinade and leave to sit for 20 minutes while you prepare the jollof. 3. Make a purée for the jollof rice. Blend all the ingredients together, then heat 2 tablespoons of olive oil in a wide saucepan and add the purée. Cook on medium heat for up to 20 minutes, until the purée is reduced and drier in texture. 4. Add the dry spices and smoked paprika to the purée, stir and cook for 5 minutes. Add the rinsed rice, stock, salt and bay leaf. 5. Preheat the oven to 200°C/gas mark 6. 6. Stir the rice well and add a little more water if needed, to completely submerge the rice. Bring to the boil, then cover and reduce the heat to low. 7. Check the rice regularly, carefully pushing the grains from the sides without stirring in order to check for water. Jollof rice needs to be cooked slowly with lots of steam – only add a little water at a time if it dries out. It is okay if it burns a little, as this will help to infuse even more smoky flavour into the rice, and someone will enjoy eating the burnt bits. Overall, it should take no more than 30 minutes to cook. 8. In the meantime, place the marinated plantain chips on a baking tray with as little liquid as possible. Bake for up to 30 minutes, checking at 15-minute intervals. Once cooked, they should be crunchy on the outside and soft on the inside. 9. To serve, fluff the jollof rice with a fork and top with the crisp kelewele. Scatter over a few thyme leaves to garnish.', 'Nigeria', 90, ' Calories : 137 , Fat : 1.79g , Carbohydrates : 27.33g , Protein : 2.96g'),
('Jerk chicken', '1. Pre-heat the oven to 190°C, Gas Mark 5. 2. Mix together all the marinade ingredients. 3. Place the chicken thighs in an ovenproof dish and smother with the marinade. Marinade for as long as possible, overnight is great if you have time. 4. Cook the chicken thighs for 30-40 minutes until brown and the sauce is sticky. 5. Fry the banana in a griddle pan until brown and softened. 6. Heat the rice as per the instructions on the pack. 7. Serve the Jerk chicken with the rice, griddled banana and scatter with shredded spring onions.', 'Caribbean', 60, 'Calories:233,Fat:13.9g,Carbohydrates:3.09g,Protein:22.76g'),
('Egusi soup', '1. Mix ground melon with water to form a paste. 2. Saute onions in palm oil. 3. Add pepper mix and locust beans, boil. 4. Add egusi paste, simmer covered. 5. Break up egusi lumps, add remaining ingredients. 6. Cook, adjust seasoning. 7. Add smoked turkey, smoked mackerel, and spinach. 8. Cook until spinach wilts. 9. Serve with Nigerian swallow or rice.', 'Nigeria', 60, 'Calories:306, Total Fat:19g, Saturated Fat:5.1g, Cholesterol:145mg, Sodium:758mg, Total Carbohydrates:9.4g, Dietary Fiber:2.8g, Protein:26g'),
('Eba', '1. Bring water to a rolling boil. 2. Add garri evenly to the water till it is absorbed. 3. Stir with your wooden spatula to your desired texture. 4. If too soft, add more garri, and if it’s too hard, you can add a bit of water. 5. After this, you can serve it by molding and adding your desired soup.', 'African', 20, 'Calories:381.5 kcal'),
('Waakye', '1. Soaking the Beans: • Add black-eyed peas to a bowl and pour in enough water to cover the beans by about one inch. • Soak beans in water overnight. They should absorb most of the water and double in size to be plump and slightly softened. 2. Cooking the Waakye: • Rinse sorghum leaves, beans, and rice, keeping them all separate. • Add rinsed leaves to a small saucepan over medium heat then pour in 3.5 cups water. • Bring water to a boil then reduce heat and simmer, covered, for 20-30 minutes to allow water to take on more color from leaves. • Remove sorghum leaves from water and raise heat to medium. Add in beans, baking soda, and sea salt and stir until dissolved. • Cover and cook for about 30 minutes or until beans have softened further and taken on some of the color. • Add rice to pot, cover, and continue to cook about 30 minutes or until water has dissipated and both rice and beans reach your desired texture and color.', 'Ghana',560, 'Calories:29, Carbohydrate:61, Protein:9g, Fat:1g,Saturated Fat:0.2g, Polyunsaturated Fat:0.2g, Monounsaturated Fat:0.2, Sodium:203m, Potassium:230m, Fiber:5, Sugar:2g, Vitamin A:9IU, Vitamin C:0.2m, Calcium:40m, Iron:2mg'),
('English Breakfast', '1. Warm the beans. Open the can of beans and warm in a small pot over low heat, stirring occasionally. 2. Cook the sausages and bacon. While the beans are warming, cook the sausages over medium to medium low, until browned and cooked through, turning as needed. Push the sausages to one side and add the bacon and fry, flipping as needed. 3. If you’re having black pudding, add it to the pan and fry, flipping once. Keep everything warm in the pan over a low flame. 4. Cook the mushrooms and tomatoes. In another pan, sear the mushrooms until brown and caramelized. Move to one side. Add the tomatoes, cut side down and sear. 5. Fry the bread and cook the eggs. Move the meats from the pan and fry the bread in the drippings until golden and crisp. Cook the eggs in the pan that the mushrooms and tomatoes were in. 6. Plate and enjoy! Scoop the beans in the middle of the plate then add the bacon at 1-2 o’clock, add the sausages at 3 o’clock, then the eggs at 6. If you have blood pudding, pop that on at 8 o’clock and then fill the rest of the plate with the tomatoes at 11 o’clock and the mushrooms at 12. Fried bread can get tucked in wherever or placed on a side plate. Enjoy!', 'Britis', 30, 'Calorie:168, Fat:116.8g, Saturated Fat:39.4, Cholesterol:466m, Sodium:4412m, Potassium:1305m, Carbohydrates:73.4, Fiber:17.5, Sugar:16.6, Protein:84.8g');


-- INSERT INTO ingredient table
INSERT INTO INGREDIENT (INGREDIENT_NAME) VALUES
('Eggs'),
('Butter'),
('Potato'),
('Cheddar Cheese'),
('Ham'),
('Canned baked beans'),
('Ground Black Pepper'),
('Olive Oil'),
('Canned tuna'),
('Mayonnaise'),
('Red Onion'),
('Red Bell Pepper'),
('Grated cheese'),
('Chopped chives'),
('Sour cream'),
('Carrot'),
('Celery ribs'),
('chili powder'),
('ground cumin'),
('smoked paprika'),
('dried oregano'),
('black beans'),
('pinto beans'),
('Tomatoes'),
('vegetable broth'),
('bay leaf'),
('fresh cilantro'),
('sherry vinegar'),
('red wine vinegar'),
('lime juice'),
('Salt'),
('chicken breasts'),
('cherry tomatoes'),
('pesto'),
('banana'),
('Ground melon'),
('locust beans'),
('Diced Tomatoes'),
('Tomato Paste'),
('garlic clove'),
('Kosher salt'),
('black pepper'),
('linguine'),
('basil'),
('rice'),
('red pepper'),
('pitted black olives'),
('goats cheese'),
('red chilli'),
('ground coriander'),
('Tabasco sauce'),
('tortilla'),
('Mixed salad'),
('fresh salsa'),
('cayenne pepper'),
('vegetable oil'),
('rump steak'),
('guacamole'),
('coriander leaves'),
('chopped tomatoes'),
('gnocchi'),
('mozzarella'),
('skinless chicken breasts'),
('plain flour'),
('chicken stock'),
('mascarpone'),
('butternut squash'),
('nutmeg'),
('lasagne sheets'),
('parmesan'),
('milk'),
('pine nut'),
('smoked bacon'),
('allspice'),
('smoked turkey'),
('Spinach'),
('carrot'),
('celery sticks'),
('mixed herbs'),
('mushrooms'),
('lean minced beef'),
('tomato purée'),
('red wine'),
('sugar'),
('unsalted butter'),
('pork sausages'),
('chestnut mushrooms'),
('soured cream'),
('wholegrain mustard'),
('beef stock'),
('dried tagliatelle'),
('parsley'),
('Jarred grilled vegetables'),
('capers'),
('raisins'),
('rigatoni'),
('penne'),
('sunflower oil'),
('ginger'),
('Greek yogurt'),
('ground almonds'),
('naan breads'),
('cooked basmati rice'),
('chicken thighs'),
('medium spice paste'),
('tikka'),
('aubergine'),
('baby aubergines'),
('garam masala'),
('turmeric'),
('plantain'),
('Smoked Mackerel'),
('garri'),
('coconut milk'),
('chapatis'),
('cumin seed'),
('coriander seed'),
('shallots'),
('coriander roots'),
('green chillies'),
('galangal'),
('lemongrass stalks'),
('lime leaves'),
('shrimp paste'),
('hoisin sauce'),
('sesame oil'),
('clear honey'),
('Chinese five-spice powder'),
('spring onions'),
('cashew nuts'),
('cooked brown rice'),
('baby new potatoes'),
('canned chickpeas'),
('romanesco broccoli'),
('cauliflower'),
('reduced fat halloumi'),
('leeks'),
('fennel'),
('garlic bulb'),
('chopped kale'),
('pistachio kernels'),
('grated parmesan'),
('lemon'),
('thin spaghetti'),
('frozen mixed vegetables'),
('turnip'),
('Jerk marinade'),
('ground cinnamon'),
('Beef stock cubes'),
('black-eyed peas/cow beans'),
('celeriac'),
('frozen peas'),
('parsnip'),
('tinned haricot beans'),
('dried haricot beans'),
('croutons'),
('Tilda Basmati rice'),
('red kidney beans'),
('scallion springs'),
('ground pimento'),
('Water'),
('scotch bonnet'),
('Tilda (Dry) Easy Cook Long grain Rice'),
('Golden Sella'),
('white onion'),
('precooked king prawns'),
('mild yellow curry powder'),
('green pepper'),
('tinned sweet corn'),
('fresh thyme leaves'),
('Tilda Basmati rice'),
('Coconut oil'),
('Yellow bell pepper'),
('orange bell pepper'),
('garden peas'),
('Turmeric'),
('All-purpose flour'),
('Lamb Shoulder with bone'),
('EVOO'),
('Chicken Stock Granules'),
('Beef Tomatoes'),
('Knorr Chicken Stock pot'),
('Craisins'),
('Coconut Cream'),
('caraway seeds'),
('Nigerian pepper mix'),
('baking soda'),
('Romano Red Peppers'),
('Banga Palm nut soup'),
('Dried shrimps'),
('Smoked catfish'),
('Fresh prawns'),
('Sweet pepper'),
('Maggi cube'),
('Banga spice'),
('Crayfish'),
('Scent leaves'),
('Cow skin (Kpomo)'),
('cardamom'),
('star anise'),
('Golden Sella Basmati rice'),
('Fresh plum tomatoes'),
('rock salt'),
('chilli flakes'),
('Squid rings'),
('Salmon fillets'),
('Cooked mussels'),
('Scallops'),
('rapeseed oil'),
('red cabbage'),
('whole sea bass'),
('tamarind paste'),
('jalapeno'),
('uda pod'),
('green beans'),
('blanched peanuts'),
('garlic powder'),
('ground ginger'),
('coconut flakes/chips'),
('Pouch Tilda Caribbean Rice and Peas'),
('boneless chicken thighs'),
('passata'),
('Palm oil'),
('dried sorghum leaves'),
('English Bacon'),
('Toast'),
('Black Pudding'),
('Heinz Beans'),
('Spaghetti'),
('Ground Beef'),
('Beef Broth'), 
('Parrot beans');

