--Up

-- user table
CREATE TABLE USER(
USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
USER_FNAME VARCHAR(35) NOT NULL,
USER_LNAME VARCHAR(35) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ACCOUNT_CREATION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- recipe table
CREATE TABLE RECIPE(
RECIPE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
RECIPE_NAME VARCHAR(50) NOT NULL,
COOKING_STEP TEXT NOT NULL,
CUISINE_TYPE VARCHAR(20) NOT NULL,
PREPARATION_TIME INTEGER NOT NULL,
NUTRITIONAL_INFO TEXT NOT NULL
);

-- saved_recipe table 
CREATE TABLE SAVED_RECIPE(
USER_ID INTEGER NOT NULL,
RECIPE_ID INTEGER NOT NULL,
DATE_SAVED DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (USER_ID, RECIPE_ID),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);

-- ingredient table
CREATE TABLE INGREDIENT(
INGREDIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
INGREDIENT_NAME VARCHAR(50) NOT NULL
);

-- recipe_ingredient table
CREATE TABLE RECIPE_INGREDIENT(
INGREDIENT_ID INTEGER NOT NULL,
RECIPE_ID INTEGER NOT NULL,
PRIMARY KEY (INGREDIENT_ID, RECIPE_ID),
FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);

-- INSERT INTO recipe table
INSERT INTO RECIPE (RECIPE_NAME, COOKING_STEP, CUISINE_TYPE, PREPARATION_TIME, NUTRITIONAL_INFO) VALUES 
('Spaghetti Bolognese', '1. Cook spaghetti according to package instructions. 2. In a large skillet, heat olive oil over medium heat. 3. Add ground beef and cook until browned. 4. Add onions, garlic, and carrots. Cook until vegetables are tender. 5. Stir in tomato paste, diced tomatoes, and beef broth. 6. Simmer for 20 minutes. 7. Serve sauce over cooked spaghetti.', 'Italian', 30, 'Calories: 450, Fat: 15g, Carbs: 50g, Protein: 25g');

-- INSERT INTO ingredient table
INSERT INTO INGREDIENT (INGREDIENT_NAME) VALUES
('Spaghetti'),
('Olive Oil'),
('Ground Beef'),
('Onions'),
('Garlic'),
('Carrots'),
('Tomato Paste'),
('Diced Tomatoes'),
('Beef Broth');