--Up

-- account table
CREATE TABLE ACCOUNT(
ACCOUNT_ID TEXT PRIMARY KEY,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD TEXT NOT NULL
);

-- recipe table
CREATE TABLE RECIPE(
RECIPE_ID TEXT PRIMARY KEY,
RECIPE_OBJECT TEXT NOT NULL
);

-- saved_recipe table 
CREATE TABLE SAVED_RECIPE(
ACCOUNT_ID TEXT NOT NULL,
RECIPE_ID TEXT NOT NULL,
PRIMARY KEY (ACCOUNT_ID, RECIPE_ID),
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
);

-- ingredient table
CREATE TABLE INGREDIENT(
INGREDIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
INGREDIENT_NAME TEXT NOT NULL,
CATEGORY VARCHAR(50) NOT NULL
);

-- INSERT INTO ingredient table
INSERT INTO INGREDIENT (INGREDIENT_NAME, CATEGORY) VALUES
('garlic', 'vegetables'),
('onion', 'vegetables'),
('scallion', 'vegetables'),
('tomato', 'vegetables'),
('bell pepper', 'vegetables'),
('potato', 'vegetables'),
('carrot', 'vegetables'),
('red onion', 'vegetables'),
('celery', 'vegetables'),
('shallot', 'vegetables'),
('spinach', 'vegetables'),
('sweet potato', 'vegetables'),
('pumpkin', 'vegetables'),
('jalapeno', 'vegetables'),
('avocado', 'vegetables'),
('zucchini', 'vegetables'),
('cherry tomato', 'vegetables'),
('sweet corn', 'vegetables'),
('broccoli', 'vegetables'),
('cucumber', 'vegetables'),
('chile pepper', 'vegetables'),
('baby greens', 'vegetables'),
('cabbage', 'vegetables'),
('cauliflower', 'vegetables'),
('asparagus', 'vegetables'),
('eggplant', 'vegetables'),
('romaine', 'vegetables'),
('fennel', 'vegetables'),
('arugula', 'vegetables'),
('leek', 'vegetables'),
('kale', 'vegetables'),
('lettuce', 'vegetables'),
('beetroot', 'vegetables'),
('butternut squash', 'vegetables'),
('brussels sprout', 'vegetables'),
('sun dried tomato', 'vegetables'),
('radish', 'vegetables'),
('red cabbage', 'vegetables'),
('summer squash', 'vegetables'),
('baby carrot', 'vegetables'),
('poblano pepper', 'vegetables'),
('artichoke', 'vegetables'),
('new potato', 'vegetables'),
('mixed greens', 'vegetables'),
('parsnip', 'vegetables'),
('mixed vegetable', 'vegetables'),
('sweet pepper', 'vegetables'),
('watercress', 'vegetables'),
('green tomato', 'vegetables'),
('mashed potatoes', 'vegetables'),
('serrano pepper', 'vegetables'),
('horseradish', 'vegetables'),
('iceberg', 'vegetables'),
('chard', 'vegetables'),
('hash browns', 'vegetables'),
('pimiento', 'vegetables'),
('napa cabbage', 'vegetables'),
('butter lettuce', 'vegetables'),
('spaghetti squash', 'vegetables'),
('celeriac', 'vegetables'),
('corn cob', 'vegetables'),
('radicchio', 'vegetables'),
('water chestnut', 'vegetables'),
('pearl onion', 'vegetables'),
('pepperoncini', 'vegetables'),
('tenderstem broccoli', 'vegetables'),
('leaf lettuce', 'vegetables'),
('cavolo nero', 'vegetables'),
('baby bok choy', 'vegetables'),
('plantain', 'vegetables'),
('endive', 'vegetables'),
('jicama', 'vegetables'),
('corn husk', 'vegetables'),
('habanero pepper', 'vegetables'),
('collard greens', 'vegetables'),
('french-fried onions', 'vegetables'),
('daikon', 'vegetables'),
('baby corn', 'vegetables'),
('broccoli rabe', 'vegetables'),
('belgian endive', 'vegetables'),
('rutabaga', 'vegetables'),
('kohlrabi', 'vegetables'),
('boston lettuce', 'vegetables'),
('fresno chile', 'vegetables'),
('microgreens', 'vegetables'),
('yam', 'vegetables'),
('ancho chile peppers', 'vegetables'),
('delicata squash', 'vegetables'),
('cress', 'vegetables'),
('anaheim pepper', 'vegetables'),
('frisee', 'vegetables'),
('broccoli slaw', 'vegetables'),
('potato flakes', 'vegetables'),
('pea shoots', 'vegetables'),
('golden beet', 'vegetables'),
('banana pepper', 'vegetables'),
('lemon', 'fruit'),
('lime', 'fruit'),
('apple', 'fruit'),
('banana', 'fruit'),
('orange', 'fruit'),
('mango', 'fruit'),
('craisins', 'fruit'),
('raisins', 'fruit'),
('peach', 'fruit'),
('pear', 'fruit'),
('pineapple', 'fruit'),
('date', 'fruit'),
('pomegranate', 'fruit'),
('coconut', 'fruit'),
('grape', 'fruit'),
('watermelon', 'fruit'),
('dried apricot', 'fruit'),
('plum', 'fruit'),
('fig', 'fruit'),
('kiwi', 'fruit'),
('apricot', 'fruit'),
('currant', 'fruit'),
('prunes', 'fruit'),
('rhubarb', 'fruit'),
('grapefruit', 'fruit'),
('mandarin', 'fruit'),
('sultanas', 'fruit'),
('cantaloupe', 'fruit'),
('tamarind', 'fruit'),
('chestnut', 'fruit'),
('passion fruit', 'fruit'),
('nectarine', 'fruit'),
('meyer lemon', 'fruit'),
('papaya', 'fruit'),
('dried fig', 'fruit'),
('dried fruit', 'fruit'),
('honeydew melon', 'fruit'),
('clementine', 'fruit'),
('persimmon', 'fruit'),
('dried mango', 'fruit'),
('banana chips', 'fruit'),
('jackfruit', 'fruit'),
('melon', 'fruit'),
('dried apple', 'fruit'),
('kumquat', 'fruit'),
('mixed fruit', 'fruit'),
('tangerine', 'fruit'),
('quince', 'fruit'),
('guava', 'fruit'),
('asian pear', 'fruit'),
('dragon fruit', 'fruit'),
('young coconut', 'fruit'),
('dried pineapple', 'fruit'),
('kaffir lime', 'fruit'),
('lychee', 'fruit'),
('star fruit', 'fruit'),
('green papaya', 'fruit'),
('dried pears', 'fruit'),
('pomelo', 'fruit'),
('chestnut puree', 'fruit'),
('prickly pear', 'fruit'),
('calamansi', 'fruit'),
('apple chips', 'fruit'),
('granadilla', 'fruit'),
('yuzu', 'fruit'),
('dried peach', 'fruit'),
('mixed peel', 'fruit'),
('kokum', 'fruit'),
('dried lime', 'fruit'),
('tangelo', 'fruit'),
('young jackfruit', 'fruit'),
('jujube', 'fruit'),
('dried lemon', 'fruit'),
('sweet lime', 'fruit'),
('honey date', 'fruit'),
('wood apple', 'fruit'),
('custard-apple', 'fruit'),
('durian', 'fruit'),
('freeze-dried apple', 'fruit'),
('ice-apple', 'fruit'),
('dried tamarind', 'fruit'),
('physalis', 'fruit'),
('tamarillo', 'fruit'),
('finger lime', 'fruit'),
('longan', 'fruit'),
('bitter orange', 'fruit'),
('feijoa', 'fruit'),
('chikoo', 'fruit'),
('dried orange slice', 'fruit'),
('dried persimmons', 'fruit'),
('fig leaves', 'fruit'),
('rambutan', 'fruit'),
('crabapple', 'fruit'),
('rose apple', 'fruit'),
('loquat', 'fruit'),
('soursop', 'fruit'),
('freeze-dried pineapple', 'fruit'),
('pluot', 'fruit'),
('bergamot orange', 'fruit'),
('hog plum', 'fruit'),
('strawberry', 'fruit'),
('blueberry', 'fruit'),
('raspberry', 'fruit'),
('cranberry', 'fruit'),
('cherry', 'fruit'),
('blackberry', 'fruit'),
('dried cherry', 'fruit'),
('sour cherry', 'fruit'),
('dried blueberries', 'fruit'),
('goji berry', 'fruit'),
('freeze-dried strawberry', 'fruit'),
('gooseberry', 'fruit'),
('freeze-dried raspberry', 'fruit'),
('lingonberry', 'fruit'),
('acai berry', 'fruit'),
('mulberry', 'fruit'),
('amla', 'fruit'),
('elderberry', 'fruit'),
('freeze-dried blueberry', 'fruit'),
('huckleberry', 'fruit'),
('dried elderberry', 'fruit'),
('barberry', 'fruit'),
('black raspberry', 'fruit'),
('dried berries', 'fruit'),
('saskatoon berry', 'fruit'),
('rosehip', 'fruit'),
('sea buckthorn', 'fruit'),
('hawthorn', 'fruit'),
('boysenberry', 'fruit'),
('cloudberry', 'fruit'),
('freeze-dried berries', 'fruit'),
('chokeberry', 'fruit'),
('aronia berry', 'fruit'),
('loganberry', 'fruit'),
('blackcurrant leaves', 'fruit'),
('haskap berry', 'fruit'),
('sloe berry', 'fruit'),
('oregon grape', 'fruit'),
('walnut', 'nuts'),
('pecan', 'nuts'),
('almond', 'nuts'),
('sesame seed', 'nuts'),
('cashew', 'nuts'),
('pine nut', 'nuts'),
('pistachio', 'nuts'),
('peanut', 'nuts'),
('chia', 'nuts'),
('flax', 'nuts'),
('slivered almonds', 'nuts'),
('pumpkin seeds', 'nuts'),
('hazelnut', 'nuts'),
('poppy seed', 'nuts'),
('sunflower seeds', 'nuts'),
('chopped nuts', 'nuts'),
('macadamia', 'nuts'),
('roasted peanuts', 'nuts'),
('hemp hearts', 'nuts'),
('mixed nuts', 'nuts'),
('nigella seeds', 'nuts'),
('brazil nut', 'nuts'),
('mixed seeds', 'nuts'),
('onion seed', 'nuts'),
('watermelon seeds', 'nuts'),
('honey-roasted peanuts', 'nuts'),
('melon seeds', 'nuts'),
('lotus seeds', 'nuts'),
('white chia', 'nuts'),
('trail mix', 'nuts'),
('basil seeds', 'nuts'),
('candlenut', 'nuts'),
('peanut brittle', 'nuts'),
('jackfruit seeds', 'nuts'),
('chironji', 'nuts'),
('honey-roasted almond', 'nuts'),
('honey-roasted pecans', 'nuts'),
('toasted nuts', 'nuts'),
('tigernuts', 'nuts'),
('sriracha almond', 'nuts'),
('sunflower sprouts', 'nuts'),
('apricot kernels', 'nuts'),
('milk thistle seeds', 'nuts'),
('ginkgo nuts', 'nuts'),
('palm seeds', 'nuts'),
('keto trail mix', 'nuts'),
('wattleseeds', 'nuts'),
('barukas', 'nuts'),
('indian almond', 'nuts'),
('parmesan', 'cheese'),
('cream cheese', 'cheese'),
('cheddar', 'cheese'),
('mozzarella', 'cheese'),
('feta', 'cheese'),
('ricotta', 'cheese'),
('sharp cheddar', 'cheese'),
('blue cheese', 'cheese'),
('monterey jack', 'cheese'),
('goat cheese', 'cheese'),
('fresh mozzarella', 'cheese'),
('swiss cheese', 'cheese'),
('pecorino', 'cheese'),
('gruyere', 'cheese'),
('mascarpone', 'cheese'),
('cottage cheese', 'cheese'),
('provolone', 'cheese'),
('pepper jack', 'cheese'),
('queso fresco', 'cheese'),
('american cheese', 'cheese'),
('mexican cheese blend', 'cheese'),
('brie', 'cheese'),
('paneer', 'cheese'),
('quark', 'cheese'),
('gouda', 'cheese'),
('fontina', 'cheese'),
('cotija', 'cheese'),
('asiago', 'cheese'),
('chevre', 'cheese'),
('neufchatel', 'cheese'),
('smoked cheese', 'cheese'),
('italian cheese blend', 'cheese'),
('manchego', 'cheese'),
('halloumi', 'cheese'),
('herb cream cheese', 'cheese'),
('havarti', 'cheese'),
('colby', 'cheese'),
('burrata', 'cheese'),
('string cheese', 'cheese'),
('grana-padano', 'cheese'),
('camembert', 'cheese'),
('muenster', 'cheese'),
('soft cheese', 'cheese'),
('stilton', 'cheese'),
('raclette', 'cheese'),
('cheddar-jack cheese', 'cheese'),
('colby-jack cheese', 'cheese'),
('taleggio', 'cheese'),
('jarlsberg cheese', 'cheese'),
('creamy cheese wedge', 'cheese'),
('labneh', 'cheese'),
('edam', 'cheese'),
('oaxaca', 'cheese'),
('cheese powder', 'cheese'),
('fromage blanc', 'cheese'),
('marble cheese', 'cheese'),
('kefalotyri', 'cheese'),
('leicester', 'cheese'),
('seasoned feta cheese', 'cheese'),
('mizithra', 'cheese'),
('asadero', 'cheese'),
('lancashire', 'cheese'),
('kasseri', 'cheese'),
('sheep cheese', 'cheese'),
('babybel', 'cheese'),
('scamorza', 'cheese'),
('longhorn', 'cheese'),
('comté', 'cheese'),
('wensleydale', 'cheese'),
('cheshire cheese', 'cheese'),
('graviera', 'cheese'),
('cambozola', 'cheese'),
('chenna', 'cheese'),
('anthotyro', 'cheese'),
('garlic-and-herb goat cheese', 'cheese'),
('hard goat cheese', 'cheese'),
('amul cheese', 'cheese'),
('kashkaval', 'cheese'),
('reblochon', 'cheese'),
('robiola', 'cheese'),
('manouri', 'cheese'),
('queso quesadilla', 'cheese'),
('quick-melt cheese', 'cheese'),
('brick cheese', 'cheese'),
('farmer''s cheese', 'cheese'),
('mimolette', 'cheese'),
('panela cheese', 'cheese'),
('bergkäse', 'cheese'),
('caciocavallo', 'cheese'),
('vacherin', 'cheese'),
('brown cheese', 'cheese'),
('fontal', 'cheese'),
('gloucester', 'cheese'),
('derby cheese', 'cheese'),
('flemish cheese', 'cheese'),
('truffle cheese', 'cheese'),
('epoisses cheese', 'cheese'),
('limburger', 'cheese'),
('petit-suisse', 'cheese'),
('port salut', 'cheese'),
('butter', 'dairy'),
('egg', 'dairy'),
('milk', 'dairy'),
('heavy cream', 'dairy'),
('sour cream', 'dairy'),
('buttermilk', 'dairy'),
('yogurt', 'dairy'),
('greek yogurt', 'dairy'),
('cream', 'dairy'),
('whipped cream', 'dairy'),
('ghee', 'dairy'),
('shortening', 'dairy'),
('half and half', 'dairy'),
('sweetened condensed milk', 'dairy'),
('condensed milk', 'dairy'),
('ice cream', 'dairy'),
('margarine', 'dairy'),
('creme fraiche', 'dairy'),
('frosting', 'dairy'),
('milk powder', 'dairy'),
('curd', 'dairy'),
('thickened cream', 'dairy'),
('lemon curd', 'dairy'),
('custard', 'dairy'),
('dulce de leche', 'dairy'),
('chocolate frosting', 'dairy'),
('kefir', 'dairy'),
('sherbet', 'dairy'),
('chocolate milk', 'dairy'),
('hung curd', 'dairy'),
('liquid egg substitute', 'dairy'),
('whey', 'dairy'),
('quail egg', 'dairy'),
('buttermilk powder', 'dairy'),
('frozen yogurt', 'dairy'),
('khoya', 'dairy'),
('coffee creamer', 'dairy'),
('clotted cream', 'dairy'),
('goat milk', 'dairy'),
('cheese curd', 'dairy'),
('milk cream', 'dairy'),
('sour milk', 'dairy'),
('ganache', 'dairy'),
('duck egg', 'dairy'),
('salted egg', 'dairy'),
('skyr', 'dairy'),
('pumpkin spice coffee creamer', 'dairy'),
('yogurt starter', 'dairy'),
('honey greek yogurt', 'dairy'),
('lime curd', 'dairy'),
('raw milk', 'dairy'),
('powdered coffee creamer', 'dairy'),
('milkfat', 'dairy'),
('rainbow sherbet', 'dairy'),
('strawberry frosting', 'dairy'),
('amul butter', 'dairy'),
('goat yogurt', 'dairy'),
('honey butter', 'dairy'),
('cajetal', 'dairy'),
('strawberry cream cheese', 'dairy'),
('goat butter', 'dairy'),
('cookies n cream ice cream', 'dairy'),
('century egg', 'dairy'),
('orange curd', 'dairy'),
('starter culture', 'dairy'),
('dahi', 'dairy'),
('cinnamon sugar butter spread', 'dairy'),
('bulgarian yogurt', 'dairy'),
('vendermine mocha creamer', 'dairy'),
('tvorog', 'dairy'),
('chantilly', 'dairy'),
('liquid rennet', 'dairy'),
('chocolate milk powder', 'dairy'),
('sheep''s milk yoghurt', 'dairy'),
('strawberry milk', 'dairy'),
('ayran', 'dairy'),
('buffalo milk', 'dairy'),
('yogurt drink', 'dairy'),
('cuajada', 'dairy'),
('passion-fruit curd', 'dairy'),
('sheep milk', 'dairy'),
('vanilla milk', 'dairy'),
('kashk', 'dairy'),
('pickled egg', 'dairy'),
('yoplait whips', 'dairy'),
('goat kefir', 'dairy'),
('lebneh', 'dairy'),
('niter kibbeh', 'dairy'),
('ostrich egg', 'dairy'),
('coconut milk', 'dairy-Free'),
('almond milk', 'dairy-Free'),
('almond butter', 'dairy-Free'),
('tofu', 'dairy-Free'),
('coconut cream', 'dairy-Free'),
('vegan butter', 'dairy-Free'),
('non-dairy milk', 'dairy-Free'),
('soy milk', 'dairy-Free'),
('extra firm tofu', 'dairy-Free'),
('silken tofu', 'dairy-Free'),
('coconut butter', 'dairy-Free'),
('kala namak salt', 'dairy-Free'),
('egg replacer', 'dairy-Free'),
('vegan mayonnaise', 'dairy-Free'),
('cashew butter', 'dairy-Free'),
('tempeh', 'dairy-Free'),
('vegan cream cheese', 'dairy-Free'),
('coconut yogurt', 'dairy-Free'),
('vegan parmesan', 'dairy-Free'),
('non-dairy yogurt', 'dairy-Free'),
('seed butter', 'dairy-Free'),
('vegan cheese', 'dairy-Free'),
('nut butter', 'dairy-Free'),
('oat milk', 'dairy-Free'),
('cashew milk', 'dairy-Free'),
('rice milk', 'dairy-Free'),
('vegan sour cream', 'dairy-Free'),
('vegan worcestershire', 'dairy-Free'),
('textured vegetable protein', 'dairy-Free'),
('non-dairy creamer', 'dairy-Free'),
('vegan mozzarella', 'dairy-Free'),
('soy yogurt', 'dairy-Free'),
('coconut whipped cream', 'dairy-Free'),
('vegan sausage', 'dairy-Free'),
('smoked tofu', 'dairy-Free'),
('coconut milk powder', 'dairy-Free'),
('seitan', 'dairy-Free'),
('non-dairy whipped topping', 'dairy-Free'),
('nut milk', 'dairy-Free'),
('soy cream', 'dairy-Free'),
('non-dairy cream', 'dairy-Free'),
('vegan ground beef', 'dairy-Free'),
('condensed coconut milk', 'dairy-Free'),
('vegan burger patty', 'dairy-Free'),
('vegan bacon', 'dairy-Free'),
('soy curls', 'dairy-Free'),
('vegan pesto', 'dairy-Free'),
('vegan feta', 'dairy-Free'),
('soy chorizo', 'dairy-Free'),
('hazelnut butter', 'dairy-Free'),
('vegan ranch', 'dairy-Free'),
('vegetarian oyster sauce', 'dairy-Free'),
('hemp milk', 'dairy-Free'),
('vegan beef', 'dairy-Free'),
('vegan chicken', 'dairy-Free'),
('dairy-free ice-cream', 'dairy-Free'),
('marinated tofu', 'dairy-Free'),
('vegetable suet', 'dairy-Free'),
('coconut paste', 'dairy-Free'),
('almond-coconut milk', 'dairy-Free'),
('vegan fish sauce', 'dairy-Free'),
('vegetarian hot dog', 'dairy-Free'),
('hazelnut milk', 'dairy-Free'),
('vegan caesar dressing', 'dairy-Free'),
('vegan meatballs', 'dairy-Free'),
('quorn', 'dairy-Free'),
('maple almond butter', 'dairy-Free'),
('soy milk powder', 'dairy-Free'),
('almond creamer', 'dairy-Free'),
('almond-milk yogurt', 'dairy-Free'),
('falafel mix', 'dairy-Free'),
('vegan cream cheese frosting', 'dairy-Free'),
('vegan gravy', 'dairy-Free'),
('coconut bacon', 'dairy-Free'),
('cashew cheese sauce', 'dairy-Free'),
('coconut fat', 'dairy-Free'),
('soy-free butter', 'dairy-Free'),
('vegan nutella', 'dairy-Free'),
('cashewgurt', 'dairy-Free'),
('hazelnut creamer', 'dairy-Free'),
('tofurky', 'dairy-Free'),
('vegan tzatziki', 'dairy-Free'),
('cashew cream cheese', 'dairy-Free'),
('coconut cream powder', 'dairy-Free'),
('flax milk', 'dairy-Free'),
('macadamia butter', 'dairy-Free'),
('cricket flour', 'dairy-Free'),
('okara', 'dairy-Free'),
('protein drink', 'dairy-Free'),
('egg tofu', 'dairy-Free'),
('macadamia milk', 'dairy-Free'),
('vegan ham', 'dairy-Free'),
('cashew sour cream', 'dairy-Free'),
('vegan taco meat', 'dairy-Free'),
('walnut taco meat', 'dairy-Free'),
('ready-made falafel', 'dairy-Free'),
('vegan yogurt starter', 'dairy-Free'),
('banana milk', 'dairy-Free'),
('cinnamon leaf', 'dairy-Free'),
('latik', 'dairy-Free'),
('bacon', 'meat'),
('ground beef', 'meat'),
('beef steak', 'meat'),
('deli ham', 'meat'),
('pork chops', 'meat'),
('sweet italian sausage', 'meat'),
('pork fillet', 'meat'),
('prosciutto', 'meat'),
('beef roast', 'meat'),
('sausage', 'meat'),
('ground pork', 'meat'),
('beef stew meat', 'meat'),
('pepperoni', 'meat'),
('chorizo', 'meat'),
('pancetta', 'meat'),
('pork shoulder', 'meat'),
('pork loin', 'meat'),
('ground lamb', 'meat'),
('mutton', 'meat'),
('smoked sausage', 'meat'),
('pork ribs', 'meat'),
('breakfast sausage', 'meat'),
('hot dog', 'meat'),
('beef sirloin', 'meat'),
('salami', 'meat'),
('brisket', 'meat'),
('leg of lamb', 'meat'),
('kielbasa', 'meat'),
('beef short ribs', 'meat'),
('pork belly', 'meat'),
('hot italian sausage', 'meat'),
('andouille', 'meat'),
('boneless lamb', 'meat'),
('pork roast', 'meat'),
('ground pork sausage', 'meat'),
('ground sausage', 'meat'),
('roast beef', 'meat'),
('bacon bits', 'meat'),
('pork spare ribs', 'meat'),
('lamb chops', 'meat'),
('lamb shoulder', 'meat'),
('beef ribs', 'meat'),
('bone-in ham', 'meat'),
('veal steak', 'meat'),
('pork butt', 'meat'),
('canadian bacon', 'meat'),
('beef sausage', 'meat'),
('lamb shank', 'meat'),
('ham steak', 'meat'),
('venison', 'meat'),
('pulled pork', 'meat'),
('bratwurst', 'meat'),
('ham hock', 'meat'),
('frozen meatballs', 'meat'),
('mixed ground meat', 'meat'),
('rabbit', 'meat'),
('pork cutlets', 'meat'),
('veal cutlet', 'meat'),
('soup bones', 'meat'),
('lamb loin', 'meat'),
('country style ribs', 'meat'),
('pork back ribs', 'meat'),
('mexican chorizo', 'meat'),
('smoked ham hock', 'meat'),
('black forest ham', 'meat'),
('raw chorizo', 'meat'),
('oxtail', 'meat'),
('beef liver', 'meat'),
('rack of lamb', 'meat'),
('serrano ham', 'meat'),
('pastrami', 'meat'),
('back bacon', 'meat'),
('salt pork', 'meat'),
('ground venison', 'meat'),
('blood sausage', 'meat'),
('mortadella', 'meat'),
('dried beef', 'meat'),
('boneless beef short ribs', 'meat'),
('bologna', 'meat'),
('burger patty', 'meat'),
('sausage patty', 'meat'),
('veal roast', 'meat'),
('pork stew meat', 'meat'),
('beef shoulder', 'meat'),
('hard salami', 'meat'),
('cocktail sausage', 'meat'),
('veal shank', 'meat'),
('lap cheong', 'meat'),
('fresh sausage', 'meat'),
('gammon joint', 'meat'),
('beef shank', 'meat'),
('boneless ham', 'meat'),
('country ham', 'meat'),
('ground bison', 'meat'),
('smoked pork chop', 'meat'),
('lamb neck', 'meat'),
('beef suet', 'meat'),
('pork neck', 'meat'),
('steak tips', 'meat'),
('veal chops', 'meat'),
('chicken breast', 'meat'),
('cooked chicken', 'meat'),
('chicken thighs', 'meat'),
('ground turkey', 'meat'),
('boneless skinless chicken thighs', 'meat'),
('whole chicken', 'meat'),
('whole turkey', 'meat'),
('chicken wings', 'meat'),
('turkey breast', 'meat'),
('ground chicken', 'meat'),
('rotisserie chicken', 'meat'),
('chicken tenders', 'meat'),
('turkey sausage', 'meat'),
('chicken sausage', 'meat'),
('turkey bacon', 'meat'),
('duck', 'meat'),
('duck breast', 'meat'),
('deli turkey', 'meat'),
('cornish hen', 'meat'),
('chicken livers', 'meat'),
('smoked turkey', 'meat'),
('chicken quarters', 'meat'),
('ground turkey sausage', 'meat'),
('quail', 'meat'),
('chicken lec', 'meat'),
('turkey meat', 'meat'),
('smoked turkey sausage', 'meat'),
('smoked chicken', 'meat'),
('turkey thigh', 'meat'),
('turkey leg', 'meat'),
('goose', 'meat'),
('pheasant', 'meat'),
('turkey pepperoni', 'meat'),
('chicken bones', 'meat'),
('chicken nuggets', 'meat'),
('turkey meatballs', 'meat'),
('chicken giblets', 'meat'),
('turkey wing', 'meat'),
('turkey giblets', 'meat'),
('turkey neck', 'meat'),
('chicken andouille', 'meat'),
('turkey burger', 'meat'),
('chicken gizzards', 'meat'),
('smoked turkey leg', 'meat'),
('popcorn chicken', 'meat'),
('chicken italian sausage', 'meat'),
('ostrich', 'meat'),
('turkey kielbasa', 'meat'),
('chicken feet', 'meat'),
('chicken-apple sausage', 'meat'),
('deli chicken', 'meat'),
('pulled chicken', 'meat'),
('smoked duck breast', 'meat'),
('wild game bird', 'meat'),
('pigeon', 'meat'),
('chicken necks', 'meat'),
('duck confit', 'meat'),
('turkey liver', 'meat'),
('roast duck', 'meat'),
('chicken meatballs', 'meat'),
('chicken teriyaki', 'meat'),
('guinea fowl', 'meat'),
('smoked turkey wings', 'meat'),
('duck liver', 'meat'),
('chicken curry-cut', 'meat'),
('chicken schnitzel', 'meat'),
('chicken roast', 'meat'),
('grouse', 'meat'),
('turkey bones', 'meat'),
('turkey lunch meat', 'meat'),
('goose liver', 'meat'),
('turkey roast', 'meat'),
('capon', 'meat'),
('young chicken', 'meat'),
('cooked duck', 'meat'),
('smoked turkey bacon', 'meat'),
('chicken bacon', 'meat'),
('parmesan-crusted chicken', 'meat'),
('turkey hot dog', 'meat'),
('turkey rissoles', 'meat'),
('chicken kebab', 'meat'),
('chicken ham', 'meat'),
('chicken chorizo', 'meat'),
('turkey taco meat', 'meat'),
('chicken frames', 'meat'),
('duck neck', 'meat'),
('pulled turkey', 'meat'),
('chicken gyros', 'meat'),
('chicken patty', 'meat'),
('chicken ribs', 'meat'),
('salmon', 'seafood'),
('smoked salmon', 'seafood'),
('cod', 'seafood'),
('tilapia', 'seafood'),
('tuna steak', 'seafood'),
('whitefish', 'seafood'),
('halibut', 'seafood'),
('red snapper', 'seafood'),
('sea bass', 'seafood'),
('trout', 'seafood'),
('fish fillets', 'seafood'),
('catfish', 'seafood'),
('surimi', 'seafood'),
('swordfish', 'seafood'),
('sardines', 'seafood'),
('sole', 'seafood'),
('mahi mahi', 'seafood'),
('mackerel', 'seafood'),
('smoked trout', 'seafood'),
('haddock', 'seafood'),
('caviar', 'seafood'),
('monkfish', 'seafood'),
('smoked haddock', 'seafood'),
('flounder', 'seafood'),
('hot-smoked salmon', 'seafood'),
('hake', 'seafood'),
('perch', 'seafood'),
('salt cod', 'seafood'),
('pollock', 'seafood'),
('smoked mackerel', 'seafood'),
('sea bream', 'seafood'),
('rainbow trout', 'seafood'),
('cuttlefish', 'seafood'),
('grouper', 'seafood'),
('herring', 'seafood'),
('salmon roe', 'seafood'),
('carp', 'seafood'),
('steelhead trout', 'seafood'),
('barramundi', 'seafood'),
('roe', 'seafood'),
('black cod', 'seafood'),
('orange roughy', 'seafood'),
('kingfish', 'seafood'),
('turbot', 'seafood'),
('dried anchovy', 'seafood'),
('rockfish', 'seafood'),
('pomfret', 'seafood'),
('bangus', 'seafood'),
('branzino', 'seafood'),
('battered fish', 'seafood'),
('arctic char', 'seafood'),
('fresh anchovy', 'seafood'),
('lemon sole', 'seafood'),
('eel', 'seafood'),
('pickled herring', 'seafood'),
('yellowtail', 'seafood'),
('pike', 'seafood'),
('swai fish', 'seafood'),
('walleye', 'seafood'),
('john dory', 'seafood'),
('fresh mackerel', 'seafood'),
('salmon trout', 'seafood'),
('smoked eel', 'seafood'),
('basa fish', 'seafood'),
('sturgeon', 'seafood'),
('bluefish', 'seafood'),
('fish balls', 'seafood'),
('red mullet', 'seafood'),
('gurnard', 'seafood'),
('plaice', 'seafood'),
('smoked fish', 'seafood'),
('flathead', 'seafood'),
('pompano', 'seafood'),
('rohu fish', 'seafood'),
('salted salmon', 'seafood'),
('salt fish', 'seafood'),
('whiting', 'seafood'),
('dried fish', 'seafood'),
('fish cake', 'seafood'),
('fish heads', 'seafood'),
('nile perch', 'seafood'),
('smoked herring', 'seafood'),
('salmon burger meat', 'seafood'),
('shark meat', 'seafood'),
('smoked tuna', 'seafood'),
('garoupa', 'seafood'),
('gilt-head bream', 'seafood'),
('zander', 'seafood'),
('amberjack', 'seafood'),
('pangasius', 'seafood'),
('salt herring', 'seafood'),
('soused herring', 'seafood'),
('bottarga', 'seafood'),
('korean fish cake', 'seafood'),
('mullet', 'seafood'),
('fish pie mix', 'seafood'),
('galunggong', 'seafood'),
('skipjack tuna', 'seafood'),
('tinapa', 'seafood'),
('tiny fish', 'seafood'),
('shrimp', 'seafood'),
('squid', 'seafood'),
('nori', 'seafood'),
('octopus', 'seafood'),
('soft-shell crab', 'seafood'),
('prawns', 'seafood'),
('crab', 'seafood'),
('lobster', 'seafood'),
('scallop', 'seafood'),
('mussel', 'seafood'),
('clam', 'seafood'),
('oyster', 'seafood'),
('lobster tail', 'seafood'),
('crawfish', 'seafood'),
('dried shrimp', 'seafood'),
('kombu', 'seafood'),
('bay scallop', 'seafood'),
('wakame', 'seafood'),
('mixed seafood', 'seafood'),
('scampi', 'seafood'),
('king crab', 'seafood'),
('squid ink', 'seafood'),
('dulse seaweed', 'seafood'),
('baby squid', 'seafood'),
('roasted seaweed', 'seafood'),
('kelp', 'seafood'),
('smoked oyster', 'seafood'),
('yaki-nori', 'seafood'),
('conch', 'seafood'),
('salted shrimp', 'seafood'),
('arame', 'seafood'),
('calamari steak', 'seafood'),
('sea urchin', 'seafood'),
('kizami nori', 'seafood'),
('mud crab', 'seafood'),
('seaweed salad', 'seafood'),
('hijiki', 'seafood'),
('abalone', 'seafood'),
('dulse', 'seafood'),
('smoked mussel', 'seafood'),
('sea snails', 'seafood'),
('prepared crab cake', 'seafood'),
('sea lettuce', 'seafood'),
('aonori', 'seafood'),
('korean seaweed', 'seafood'),
('jellyfish', 'seafood'),
('ogo seaweed', 'seafood'),
('seaweed caviar', 'seafood'),
('shredded squid', 'seafood'),
('sea moss', 'seafood'),
('langoustine', 'seafood'),
('cinnamon', 'spices'),
('parsley', 'spices'),
('cilantro', 'spices'),
('cumin', 'spices'),
('basil', 'spices'),
('thyme', 'spices'),
('ginger root', 'spices'),
('garlic powder', 'spices'),
('oregano', 'spices'),
('nutmeg', 'spices'),
('chilli flake', 'spices'),
('chilli powder', 'spices'),
('paprika', 'spices'),
('cayenne', 'spices'),
('rosemary', 'spices'),
('bay leaf', 'spices'),
('turmeric', 'spices'),
('clove', 'spices'),
('onion powder', 'spices'),
('ginger powder', 'spices'),
('dill', 'spices'),
('chive', 'spices'),
('mint', 'spices'),
('green cardamom', 'spices'),
('smoked paprika', 'spices'),
('fresh mint', 'spices'),
('coriander powder', 'spices'),
('sage', 'spices'),
('coriander', 'spices'),
('allspice', 'spices'),
('cracked pepper', 'spices'),
('peppercorn', 'spices'),
('mustard powder', 'spices'),
('white pepper', 'spices'),
('mustard seed', 'spices'),
('curry leaves', 'spices'),
('fennel seed', 'spices'),
('tarragon', 'spices'),
('saffron', 'spices'),
('asafoetida', 'spices'),
('star anise', 'spices'),
('marjoram', 'spices'),
('lemongrass', 'spices'),
('caraway', 'spices'),
('garlic granules', 'spices'),
('celery seed', 'spices'),
('chipotle powder', 'spices'),
('chipotle', 'spices'),
('fenugreek', 'spices'),
('onion flake', 'spices'),
('thai chile pepper', 'spices'),
('ancho chile powder', 'spices'),
('sumac', 'spices'),
('dried parsley flakes', 'spices'),
('fenugreek seed', 'spices'),
('kashmiri red chilli', 'spices'),
('thai basil', 'spices'),
('edible flowers', 'spices'),
('kaffir lime leaves', 'spices'),
('aniseed', 'spices'),
('chervil', 'spices'),
('lavender', 'spices'),
('carom seeds', 'spices'),
('mango powder', 'spices'),
('mace', 'spices'),
('dried chive', 'spices'),
('mexican oregano', 'spices'),
('black mustard seed', 'spices'),
('black cardamom', 'spices'),
('dried chilies', 'spices'),
('saffron strands', 'spices'),
('pink peppercorn', 'spices'),
('hot paprika', 'spices'),
('lemon thyme', 'spices'),
('guajillo pepper', 'spices'),
('galangal', 'spices'),
('dried cilantro', 'spices'),
('garlic flakes', 'spices'),
('lemon balm', 'spices'),
('dill seed', 'spices'),
('green peppercorn', 'spices'),
('aleppo pepper', 'spices'),
('wasabi powder', 'spices'),
('gochugaru', 'spices'),
('savoury herb', 'spices'),
('clove powder', 'spices'),
('achiote seeds', 'spices'),
('pandan leaves', 'spices'),
('sorrel', 'spices'),
('saigon cinnamon', 'spices'),
('lemongrass paste', 'spices'),
('shiso', 'spices'),
('celery powder', 'spices'),
('anardana', 'spices'),
('black cumin', 'spices'),
('dried orange peel', 'spices'),
('vietnamese mint', 'spices'),
('espelette pepper', 'spices'),
('lemon verbena', 'spices'),
('raw stevia', 'spices'),
('sugar', 'sugar'),
('brown sugar', 'sugar'),
('confectioners'' sugar', 'sugar'),
('honey', 'sugar'),
('maple syrup', 'sugar'),
('corn syrup', 'sugar'),
('coconut sugar', 'sugar'),
('molasses', 'sugar'),
('stevia', 'sugar'),
('agave nectar', 'sugar'),
('demerara sugar', 'sugar'),
('sugar syrup', 'sugar'),
('erythritol', 'sugar'),
('vanilla sugar', 'sugar'),
('caramel syrup', 'sugar'),
('jaggery', 'sugar'),
('chocolate syrup', 'sugar'),
('golden syrup', 'sugar'),
('cinnamon sugar', 'sugar'),
('liquid stevia', 'sugar'),
('grenadine', 'sugar'),
('coarse sugar', 'sugar'),
('salted caramel syrup', 'sugar'),
('sanding sugar', 'sugar'),
('dark corn syrup', 'sugar'),
('monk fruit sweetener', 'sugar'),
('sucralose', 'sugar'),
('coloured sugar', 'sugar'),
('blackstrap molasses', 'sugar'),
('maple sugar', 'sugar'),
('glucose', 'sugar'),
('confectioners'' sweetener', 'sugar'),
('xylitol', 'sugar'),
('brown sugar substitute', 'sugar'),
('jam sugar', 'sugar'),
('brown rice syrup', 'sugar'),
('rock sugar', 'sugar'),
('vanilla syrup', 'sugar'),
('strawberry syrup', 'sugar'),
('coconut syrup', 'sugar'),
('ginger syrup', 'sugar'),
('orgeat', 'sugar'),
('raspberry syrup', 'sugar'),
('rice malt syrup', 'sugar'),
('pancake syrup', 'sugar'),
('date syrup', 'sugar'),
('black treacle', 'sugar'),
('date paste', 'sugar'),
('mint syrup', 'sugar'),
('cinnamon syrup', 'sugar'),
('treacle', 'sugar'),
('passion fruit syrup', 'sugar'),
('rice syrup', 'sugar'),
('maple butter', 'sugar'),
('manuka honey', 'sugar'),
('blueberry syrup', 'sugar'),
('apple syrup', 'sugar'),
('allulose', 'sugar'),
('blackberry syrup', 'sugar'),
('hibiscus syrup', 'sugar'),
('cherry syrup', 'sugar'),
('fresh sugar cane', 'sugar'),
('lavender syrup', 'sugar'),
('pineapple syrup', 'sugar'),
('hazelnut syrup', 'sugar'),
('sorghum syrup', 'sugar'),
('white chocolate sauce', 'sugar'),
('pumpkin spice syrup', 'sugar'),
('glycerine', 'sugar'),
('lucuma powder', 'sugar'),
('piloncillo', 'sugar'),
('golden sugar', 'sugar'),
('cranberry syrup', 'sugar'),
('black sugar', 'sugar'),
('cane syrup', 'sugar'),
('mango syrup', 'sugar'),
('malt syrup', 'sugar'),
('hot honey', 'sugar'),
('elderberry syrup', 'sugar'),
('gula melaka', 'sugar'),
('rosemary syrup', 'sugar'),
('dark chocolate syrup', 'sugar'),
('inulin', 'sugar'),
('brown butter syrup', 'sugar'),
('flavoured stevia', 'sugar'),
('sweet''n low', 'sugar'),
('fructose', 'sugar'),
('honey powder', 'sugar'),
('berry syrup', 'sugar'),
('date sugar', 'sugar'),
('grape syrup', 'sugar'),
('mastic gum', 'sugar'),
('gum syrup', 'sugar'),
('irish cream syrup', 'sugar'),
('prickly pear syrup', 'sugar'),
('cookie butter syrup', 'sugar'),
('creamed honey', 'sugar'),
('lavender sugar', 'sugar'),
('chocolate sugar', 'sugar'),
('buttermilk syrup', 'sugar'),
('italian seasoning', 'seasonings'),
('seasoned salt', 'seasonings'),
('curry', 'seasonings'),
('garam masala', 'seasonings'),
('pumpkin pie spice', 'seasonings'),
('taco seasoning', 'seasonings'),
('cajun seasoning', 'seasonings'),
('dry ranch seasoning', 'seasonings'),
('white miso', 'seasonings'),
('himalayan salt', 'seasonings'),
('lemon & pepper seasoning', 'seasonings'),
('liquid smoke', 'seasonings'),
('poultry seasoning', 'seasonings'),
('chinese five spice', 'seasonings'),
('red curry', 'seasonings'),
('old bay seasoning', 'seasonings'),
('herbes de provence', 'seasonings'),
('all-purpose seasoning', 'seasonings'),
('chaat masala', 'seasonings'),
('creole seasoning', 'seasonings'),
('steak seasoning', 'seasonings'),
('juniper berry', 'seasonings'),
('fleur de sel', 'seasonings'),
('thai red curry paste', 'seasonings'),
('mixed herbs', 'seasonings'),
('green curry', 'seasonings'),
('barbecue seasoning', 'seasonings'),
('apple pie spice', 'seasonings'),
('zaatar', 'seasonings'),
('ras el hanout', 'seasonings'),
('seafood seasoning', 'seasonings'),
('bagel seasoning', 'seasonings'),
('chilli con carne seasoning', 'seasonings'),
('fajita seasoning', 'seasonings'),
('gravy mix', 'seasonings'),
('tandoori spice', 'seasonings'),
('pickling spice', 'seasonings'),
('garlic-pepper seasoning', 'seasonings'),
('caribbean jerk seasoning', 'seasonings'),
('pickling salt', 'seasonings'),
('garlic & herb seasoning', 'seasonings'),
('greek seasoning', 'seasonings'),
('msg', 'seasonings'),
('adobo seasoning', 'seasonings'),
('sambar powder', 'seasonings'),
('smoked salt', 'seasonings'),
('smoking wood', 'seasonings'),
('dash seasoning', 'seasonings'),
('red miso', 'seasonings'),
('hot curry', 'seasonings'),
('chilli-lime seasoning', 'seasonings'),
('salt-free seasoning', 'seasonings'),
('bouquet garni', 'seasonings'),
('yellow miso', 'seasonings'),
('carne asada seasoning', 'seasonings'),
('dukkah', 'seasonings'),
('curing salt', 'seasonings'),
('pav bhaji masala', 'seasonings'),
('mexican seasoning', 'seasonings'),
('seasoned pepper', 'seasonings'),
('chipotle seasoning', 'seasonings'),
('crab boil seasoning', 'seasonings'),
('shichimi togarashi', 'seasonings'),
('rib rub', 'seasonings'),
('truffle salt', 'seasonings'),
('biryani masala', 'seasonings'),
('furikake', 'seasonings'),
('togarashi', 'seasonings'),
('chana masala', 'seasonings'),
('meat masala', 'seasonings'),
('harissa spice blend', 'seasonings'),
('grey sea salt', 'seasonings'),
('cheese powder', 'seasonings'),
('brown miso', 'seasonings'),
('mushroom seasoning', 'seasonings'),
('gingerbread spice', 'seasonings'),
('au jus mix', 'seasonings'),
('blackening seasoning', 'seasonings'),
('lemon & herb seasoning', 'seasonings'),
('popcorn seasoning', 'seasonings'),
('pizza seasoning', 'seasonings'),
('berbere', 'seasonings'),
('chai masala', 'seasonings'),
('kitchen king masala', 'seasonings'),
('fines herbes', 'seasonings'),
('vanilla salt', 'seasonings'),
('mulling spices', 'seasonings'),
('thai seasoning', 'seasonings'),
('coffee rub', 'seasonings'),
('sriracha seasoning', 'seasonings'),
('hawaiian salt', 'seasonings'),
('tom yum paste', 'seasonings'),
('guacamole seasoning', 'seasonings'),
('mesquite seasoning', 'seasonings'),
('salad seasoning', 'seasonings'),
('beef stew seasoning', 'seasonings'),
('baharat', 'seasonings'),
('fish masala', 'seasonings'),
('flour', 'baking'),
('vanilla', 'baking'),
('baking powder', 'baking'),
('baking soda', 'baking'),
('cornstarch', 'baking'),
('yeast', 'baking'),
('dark chocolate chips', 'baking'),
('chocolate chips', 'baking'),
('whole-wheat flour', 'baking'),
('shredded coconut', 'baking'),
('almond flour', 'baking'),
('self-raising flour', 'baking'),
('cornmeal', 'baking'),
('coconut flake', 'baking'),
('baking mix', 'baking'),
('pastry flour', 'baking'),
('coconut flour', 'baking'),
('cream of tartar', 'baking'),
('cake flour', 'baking'),
('bread flour', 'baking'),
('almond meal', 'baking'),
('unbleached all-purpose flour', 'baking'),
('white baking chips', 'baking'),
('gluten-free flour', 'baking'),
('rice flour', 'baking'),
('tapioca starch', 'baking'),
('yellow cake mix', 'baking'),
('chickpea flour', 'baking'),
('xanthan gum', 'baking'),
('oat flour', 'baking'),
('whole-wheat pastry flour', 'baking'),
('candy sprinkles', 'baking'),
('chocolate cake mix', 'baking'),
('spelt', 'baking'),
('brownie mix', 'baking'),
('arrowroot flour', 'baking'),
('flaxseed meal', 'baking'),
('potato starch', 'baking'),
('butterscotch chips', 'baking'),
('peanut butter chips', 'baking'),
('crystallised ginger', 'baking'),
('buckwheat flour', 'baking'),
('brown rice flour', 'baking'),
('pectin', 'baking'),
('psyllium husk', 'baking'),
('rye flour', 'baking'),
('semolina flour', 'baking'),
('glutinous rice flour', 'baking'),
('refined flour', 'baking'),
('pancake mix', 'baking'),
('marzipan', 'baking'),
('muffin mix', 'baking'),
('toffee bits', 'baking'),
('coffee bean', 'baking'),
('cornbread mix', 'baking'),
('spice cake mix', 'baking'),
('masa harina', 'baking'),
('sorghum flour', 'baking'),
('cinnamon chips', 'baking'),
('red velvet cake mix', 'baking'),
('baking chips', 'baking'),
('sugar cookie mix', 'baking'),
('sago', 'baking'),
('matzo meal', 'baking'),
('whipped cream stabiliser', 'baking'),
('vital wheat gluten', 'baking'),
('coconut chips', 'baking'),
('cassava flour', 'baking'),
('hazelnut flour', 'baking'),
('quinoa flour', 'baking'),
('finger millet flour', 'baking'),
('meringue powder', 'baking'),
('angel food cake mix', 'baking'),
('mint baking chips', 'baking'),
('fondant', 'baking'),
('white cornmeal', 'baking'),
('gluten-free baking flour', 'baking'),
('millet flour', 'baking'),
('mincemeat', 'baking'),
('einkorn flour', 'baking'),
('self-rising cornmeal', 'baking'),
('peanut flour', 'baking'),
('gluten-free cake mix', 'baking'),
('gluten-free self-raising flour', 'baking'),
('coconut powder', 'baking'),
('carob powder', 'baking'),
('teff flour', 'baking'),
('ready-made icing', 'baking'),
('potato flour', 'baking'),
('sweet bean paste', 'baking'),
('guar gum', 'baking'),
('fruit salt', 'baking'),
('tapioca pearls', 'baking'),
('instant flour', 'baking'),
('seasoned flour', 'baking'),
('soy flour', 'baking'),
('amaranth flour', 'baking'),
('oat fibre', 'baking'),
('gluten-free panko', 'baking'),
('whole-grain oat flour', 'baking'),
('pie crust', 'pre-made'),
('puff pastry', 'pre-made'),
('refrigerated crescent rolls', 'pre-made'),
('pizza crust', 'pre-made'),
('phyllo', 'pre-made'),
('biscuit dough', 'pre-made'),
('dumpling wrapper', 'pre-made'),
('cookie dough', 'pre-made'),
('rice paper', 'pre-made'),
('graham cracker crust', 'pre-made'),
('sourdough starter', 'pre-made'),
('egg roll wrapper', 'pre-made'),
('frozen dinner roll', 'pre-made'),
('bread dough', 'pre-made'),
('mini phyllo', 'pre-made'),
('butter puff pastry', 'pre-made'),
('cinnamon roll dough', 'pre-made'),
('gyoza wrapper', 'pre-made'),
('dosa batter', 'pre-made'),
('puff pastry shells', 'pre-made'),
('wontons', 'pre-made'),
('wonton strips', 'pre-made'),
('gluten-free pizza crust', 'pre-made'),
('fresh pasta dough', 'pre-made'),
('idli batter', 'pre-made'),
('chocolate pie crust', 'pre-made'),
('croissant dough', 'pre-made'),
('tofu skins', 'pre-made'),
('kataifi', 'pre-made'),
('brisee', 'pre-made'),
('chocolate crumb crust', 'pre-made'),
('sausage rolls', 'pre-made'),
('frozen pizza rolls', 'pre-made'),
('korean rice cake', 'pre-made'),
('corn dogs', 'pre-made'),
('empanada wrapper', 'pre-made'),
('rough-puff pastry', 'pre-made'),
('sourdough discard', 'pre-made'),
('tortilla dough', 'pre-made'),
('gingerbread cookie dough', 'pre-made'),
('yufka', 'pre-made'),
('cob loaf', 'pre-made'),
('samosa sheet', 'pre-made'),
('egg Wrad', 'pre-made'),
('brick pastry', 'pre-made'),
('rolled oats', 'grains&cereal'),
('white rice', 'grains&cereal'),
('long-grain white rice', 'grains&cereal'),
('quinoa', 'grains&cereal'),
('brown rice', 'grains&cereal'),
('quick-cooking oats', 'grains&cereal'),
('cooked rice', 'grains&cereal'),
('breakfast cereal', 'grains&cereal'),
('risotto rice', 'grains&cereal'),
('rice cereal', 'grains&cereal'),
('couscous', 'grains&cereal'),
('wild rice', 'grains&cereal'),
('semolina', 'grains&cereal'),
('jasmine rice', 'grains&cereal'),
('polenta', 'grains&cereal'),
('granola cereal', 'grains&cereal'),
('bulgur', 'grains&cereal'),
('cauliflower rice', 'grains&cereal'),
('pearl barley', 'grains&cereal'),
('farro', 'grains&cereal'),
('grits', 'grains&cereal'),
('barley', 'grains&cereal'),
('wheat germ', 'grains&cereal'),
('steel cut oats', 'grains&cereal'),
('oat bran', 'grains&cereal'),
('instant rice', 'grains&cereal'),
('sushi rice', 'grains&cereal'),
('millet', 'grains&cereal'),
('glutinous rice', 'grains&cereal'),
('hominy', 'grains&cereal'),
('red quinoa', 'grains&cereal'),
('raw buckwheat', 'grains&cereal'),
('wheat bran', 'grains&cereal'),
('instant oats', 'grains&cereal'),
('poha', 'grains&cereal'),
('wheat berries', 'grains&cereal'),
('yellow rice', 'grains&cereal'),
('black rice', 'grains&cereal'),
('muesli', 'grains&cereal'),
('fine semolina', 'grains&cereal'),
('kashal', 'grains&cereal'),
('quinoa flakes', 'grains&cereal'),
('amaranth', 'grains&cereal'),
('puffed rice', 'grains&cereal'),
('cracked wheat', 'grains&cereal'),
('pearled farro', 'grains&cereal'),
('paella rice', 'grains&cereal'),
('freekeh', 'grains&cereal'),
('sorghum', 'grains&cereal'),
('red rice', 'grains&cereal'),
('idli rice', 'grains&cereal'),
('mexican rice', 'grains&cereal'),
('brown jasmine rice', 'grains&cereal'),
('cream of wheat', 'grains&cereal'),
('rice pilaf', 'grains&cereal'),
('weetabix', 'grains&cereal'),
('barnyard millet', 'grains&cereal'),
('gluten-free cereals', 'grains&cereal'),
('blue cornmeal', 'grains&cereal'),
('jambalaya rice mix', 'grains&cereal'),
('whole-grain oats', 'grains&cereal'),
('cilantro lime rice', 'grains&cereal'),
('puffed quinoa', 'grains&cereal'),
('black glutinous rice', 'grains&cereal'),
('dirty rice mix', 'grains&cereal'),
('hulled barley', 'grains&cereal'),
('finger millet', 'grains&cereal'),
('puffed wheat', 'grains&cereal'),
('broccoli rice', 'grains&cereal'),
('foxtail millet', 'grains&cereal'),
('brown long grain rice', 'grains&cereal'),
('fried rice', 'grains&cereal'),
('pearl millet', 'grains&cereal'),
('matta rice', 'grains&cereal'),
('rye berries', 'grains&cereal'),
('kodo millet', 'grains&cereal'),
('spelt flakes', 'grains&cereal'),
('oat groats', 'grains&cereal'),
('teff', 'grains&cereal'),
('chicken-flavour rice', 'grains&cereal'),
('little millet', 'grains&cereal'),
('rye flakes', 'grains&cereal'),
('puffed amaranth', 'grains&cereal'),
('coconut rice', 'grains&cereal'),
('red beans & rice mix', 'grains&cereal'),
('rice bran', 'grains&cereal'),
('spelt berry', 'grains&cereal'),
('texmati rice', 'grains&cereal'),
('amaranth flakes', 'grains&cereal'),
('puffed kamut', 'grains&cereal'),
('shirataki rice', 'grains&cereal'),
('bamboo rice', 'grains&cereal'),
('pearled sorghum', 'grains&cereal'),
('red rice poha', 'grains&cereal'),
('sona masoori rice', 'grains&cereal'),
('grünkern', 'grains&cereal'),
('jeera rice', 'grains&cereal'),
('saffron rice', 'grains&cereal'),
('fonio', 'grains&cereal'),
('peas', 'legumes'),
('green beans', 'legumes'),
('black beans', 'legumes'),
('chickpea', 'legumes'),
('kidney beans', 'legumes'),
('white beans', 'legumes'),
('lentils', 'legumes'),
('snow peas', 'legumes'),
('snap peas', 'legumes'),
('red lentils', 'legumes'),
('cannellini beans', 'legumes'),
('bean sprouts', 'legumes'),
('edamame', 'legumes'),
('green lentils', 'legumes'),
('pinto beans', 'legumes'),
('urad dal', 'legumes'),
('lima beans', 'legumes'),
('chana dal', 'legumes'),
('tava beans', 'legumes'),
('black-eyed peas', 'legumes'),
('moong dal', 'legumes'),
('sellt peas', 'legumes'),
('pigeon peas', 'legumes'),
('red beans', 'legumes'),
('mung bean sprout', 'legumes'),
('soybeans', 'legumes'),
('mung beans', 'legumes'),
('string beans', 'legumes'),
('yellow split peas', 'legumes'),
('black lentils', 'legumes'),
('borlotti beans', 'legumes'),
('aquafaba', 'legumes'),
('chana', 'legumes'),
('snake beans', 'legumes'),
('yellow lentils', 'legumes'),
('fermented black beans', 'legumes'),
('kala chana', 'legumes'),
('mixed beans', 'legumes'),
('black gram', 'legumes'),
('wax beans', 'legumes'),
('dried peas', 'legumes'),
('white pea', 'legumes'),
('lentil sprouts', 'legumes'),
('pink beans', 'legumes'),
('black soybeans', 'legumes'),
('field peas', 'legumes'),
('gigantes', 'legumes'),
('flageolets', 'legumes'),
('horse gram', 'legumes'),
('green chickpea', 'legumes'),
('soy sprouts', 'legumes'),
('brown beans', 'legumes'),
('cluster beans', 'legumes'),
('mayocoba beans', 'legumes'),
('winged beans', 'legumes'),
('castelluccio lentils', 'legumes'),
('golden wax beans', 'legumes'),
('moth beans', 'legumes'),
('hara chanal', 'legumes'),
('hyacinth beans', 'legumes'),
('lupini beans', 'legumes'),
('chickpea sprouts', 'legumes'),
('natte', 'legumes'),
('petai', 'legumes'),
('sugar beans', 'legumes'),
('scarlet runner beans', 'legumes'),
('honey beans', 'legumes'),
('soy flakes', 'legumes'),
('short-cut pasta', 'pasta'),
('spaghetti', 'pasta'),
('macaroni', 'pasta'),
('egg noodle', 'pasta'),
('spiral pasta', 'pasta'),
('lasagna', 'pasta'),
('linguine', 'pasta'),
('fettuccine', 'pasta'),
('orzo', 'pasta'),
('pasta shell', 'pasta'),
('bow-tie pasta', 'pasta'),
('tortellini', 'pasta'),
('noodle', 'pasta'),
('rice noodles', 'pasta'),
('rigatoni', 'pasta'),
('gnocchi', 'pasta'),
('angel hair pasta', 'pasta'),
('ramen noodles', 'pasta'),
('vermicelli', 'pasta'),
('tagliatelle', 'pasta'),
('ravioli', 'pasta'),
('ziti', 'pasta'),
('soba noodles', 'pasta'),
('orecchiette', 'pasta'),
('israeli couscous', 'pasta'),
('zoodles', 'pasta'),
('udon noodles', 'pasta'),
('ditalini', 'pasta'),
('rice vermicelli', 'pasta'),
('pappardelle', 'pasta'),
('glass noodles', 'pasta'),
('gluten-free pasta', 'pasta'),
('mac n cheese', 'pasta'),
('penne rigate', 'pasta'),
('manicotti', 'pasta'),
('bucatini', 'pasta'),
('cannelloni', 'pasta'),
('thai rice noodles', 'pasta'),
('rotelle', 'pasta'),
('shirataki noodles', 'pasta'),
('brown rice pasta', 'pasta'),
('chicken ramen', 'pasta'),
('pierogi', 'pasta'),
('soup pasta', 'pasta'),
('cavatelli', 'pasta'),
('sweet potato noodles', 'pasta'),
('acini di pepe', 'pasta'),
('instant noodle', 'pasta'),
('somen noodles', 'pasta'),
('radiatore', 'pasta'),
('gluten-free noodles', 'pasta'),
('yakisoba noodles', 'pasta'),
('beef ravioli', 'pasta'),
('spaetzle', 'pasta'),
('hakka noodles', 'pasta'),
('kluski noodles', 'pasta'),
('fideo pasta', 'pasta'),
('kelp noodles', 'pasta'),
('rice-a-roni', 'pasta'),
('paccheri', 'pasta'),
('pasta salad mix', 'pasta'),
('beef ramen', 'pasta'),
('matzo farfel', 'pasta'),
('yolk-free noodles', 'pasta'),
('black bean pasta', 'pasta'),
('spinach fettuccine', 'pasta'),
('banh pho', 'pasta'),
('frozen dumplings', 'pasta'),
('fregola', 'pasta'),
('beef tortellini', 'pasta'),
('cauliflower gnocchi', 'pasta'),
('butternut squash noodles', 'pasta'),
('misua', 'pasta'),
('palmini', 'pasta'),
('trahanas', 'pasta'),
('busiate', 'pasta'),
('lobster ravioli', 'pasta'),
('mafalde', 'pasta'),
('trottole', 'pasta'),
('casarecce', 'pasta'),
('mandu', 'pasta'),
('pork ramen', 'pasta'),
('pot pie noodle', 'pasta'),
('mie noodle', 'pasta'),
('semiya', 'pasta'),
('bean pasta', 'pasta'),
('bean sheets', 'pasta'),
('hilopites', 'pasta'),
('naengmyeon noodles', 'pasta'),
('yuba noodles', 'pasta'),
('jjolmyeon', 'pasta'),
('quinoa pasta', 'pasta'),
('squash ravioli', 'pasta'),
('bread', 'bread'),
('bread crumbs', 'bread'),
('panko', 'bread'),
('flour tortillas', 'bread'),
('corn tortillas', 'bread'),
('crackers', 'bread'),
('baguette', 'bread'),
('tortilla chips', 'bread'),
('pretzels', 'bread'),
('pita', 'bread'),
('sourdough bread', 'bread'),
('seasoned bread crumbs', 'bread'),
('rustic italian bread', 'bread'),
('popcorn', 'bread'),
('croutons', 'bread'),
('whole-wheat tortillas', 'bread'),
('english muffin', 'bread'),
('brioche', 'bread'),
('rye bread', 'bread'),
('flatbread', 'bread'),
('dry-roasted peanuts', 'bread'),
('stuffing mix', 'bread'),
('potato chips', 'bread'),
('taco shells', 'bread'),
('cornbread', 'bread'),
('unpopped popcorn', 'bread'),
('tater tots', 'bread'),
('corn chips', 'bread'),
('bagel', 'bread'),
('croissants', 'bread'),
('pork rinds', 'bread'),
('pumpernickel', 'bread'),
('sweet bread', 'bread'),
('gluten free bread', 'bread'),
('pita chips', 'bread'),
('hawaiian rolls', 'bread'),
('potato bread', 'bread'),
('focaccia', 'bread'),
('breadsticks', 'bread'),
('muffin', 'bread'),
('tostada shells', 'bread'),
('gluten-free bread crumbs', 'bread'),
('crispy fried onions', 'bread'),
('yeast extract spread', 'bread'),
('garlic bread', 'bread'),
('matzo', 'bread'),
('challah', 'bread'),
('roasted gram', 'bread'),
('cheese crackers', 'bread'),
('panettone', 'bread'),
('crostini', 'bread'),
('rice cake', 'bread'),
('gluten-free tortillas', 'bread'),
('sev', 'bread'),
('sweet potato fries', 'bread'),
('corn muffin', 'bread'),
('papad', 'bread'),
('vegetable chips', 'bread'),
('spinach wraps', 'bread'),
('plantain chips', 'bread'),
('roasted chickpeas', 'bread'),
('pretzel bun', 'bread'),
('boboli', 'bread'),
('cheetos', 'bread'),
('crumpet', 'bread'),
('chapati', 'bread'),
('seed bread', 'bread'),
('keto bread', 'bread'),
('bread bowl', 'bread'),
('cornbread stuffing mix', 'bread'),
('low-carb wraps', 'bread'),
('milk bread', 'bread'),
('frozen onion rings', 'bread'),
('sprouted grain bread', 'bread'),
('rice crackers', 'bread'),
('rusks', 'bread'),
('corn nuts', 'bread'),
('pav bun', 'bread'),
('banana bread', 'bread'),
('sprouted bread', 'bread'),
('fruit bread', 'bread'),
('crispbread', 'bread'),
('roti bread', 'bread'),
('prawn crackers', 'bread'),
('chocolate muffin', 'bread'),
('popcorn shrimp', 'bread'),
('ezekiel bread', 'bread'),
('melba toast', 'bread'),
('bao bun', 'bread'),
('naan', 'bread'),
('wasabi peas', 'bread'),
('melba toast', 'bread'),
('bao bun', 'bread'),
('wasabi peas', 'bread'),
('yorkshire pudding', 'bread'),
('arabic bread', 'bread'),
('barley rusks', 'bread'),
('zwieback', 'bread'),
('oven chips', 'bread'),
('taco kit', 'bread'),
('gluten free pita', 'bread'),
('oatcakes', 'bread'),
('ready-made arepas', 'bread'),
('olive oil', 'oils&fats'),
('vegetable oil', 'oils&fats'),
('extra virgin olive oil', 'oils&fats'),
('canola oil', 'oils&fats'),
('coconut oil', 'oils&fats'),
('cooking spray', 'oils&fats'),
('sesame oil', 'oils&fats'),
('frying oil', 'oils&fats'),
('sunflower oil', 'oils&fats'),
('avocado oil', 'oils&fats'),
('toasted sesame oil', 'oils&fats'),
('peanut oil', 'oils&fats'),
('grapeseed oil', 'oils&fats'),
('lard', 'oils&fats'),
('pork fat', 'oils&fats'),
('corn oil', 'oils&fats'),
('virgin coconut oil', 'oils&fats'),
('mustard oil', 'oils&fats'),
('chilli oil', 'oils&fats'),
('walnut oil', 'oils&fats'),
('garlic oil', 'oils&fats'),
('truffle oil', 'oils&fats'),
('safflower oil', 'oils&fats'),
('cacao butter', 'oils&fats'),
('salad oil', 'oils&fats'),
('duck fat', 'oils&fats'),
('rice bran oil', 'oils&fats'),
('soybean oil', 'oils&fats'),
('white truffle oil', 'oils&fats'),
('medium-chain triglyceride', 'oils&fats'),
('butter-flavoured cooking spray', 'oils&fats'),
('flaxseed oil', 'oils&fats'),
('pumpkin seed oil', 'oils&fats'),
('hazelnut oil', 'oils&fats'),
('coconut oil spray', 'oils&fats'),
('almond oil', 'oils&fats'),
('lemon oil', 'oils&fats'),
('macadamia oil', 'oils&fats'),
('goose fat', 'oils&fats'),
('palm oil', 'oils&fats'),
('basil oil', 'oils&fats'),
('schmaltz', 'oils&fats'),
('tallow', 'oils&fats'),
('pistachio oil', 'oils&fats'),
('herb-infused olive oil', 'oils&fats'),
('hot sesame oil', 'oils&fats'),
('pecan oil', 'oils&fats'),
('argan oil', 'oils&fats'),
('beef fat', 'oils&fats'),
('roasted peanut oil', 'oils&fats'),
('crisco oil', 'oils&fats'),
('shea butter', 'oils&fats'),
('black sesame oil', 'oils&fats'),
('red palm oil', 'oils&fats'),
('lamb fat', 'oils&fats'),
('sichuan peppercorn oil', 'oils&fats'),
('castor oil', 'oils&fats'),
('shallot oil', 'oils&fats'),
('achiote oil', 'oils&fats'),
('jojoba oil', 'oils&fats'),
('wheat germ oil', 'oils&fats'),
('blood orange olive oil', 'oils&fats'),
('oregano oil', 'oils&fats'),
('hemp seed oil', 'oils&fats'),
('cottonseed oil', 'oils&fats'),
('ginger oil', 'oils&fats'),
('rosehip seed oil', 'oils&fats'),
('marula oil', 'oils&fats'),
('moringa seed oil', 'oils&fats'),
('white cacao butter', 'oils&fats'),
('black seed oil', 'oils&fats'),
('mayonnaise', 'dressings'),
('apple cider vinegar', 'dressings'),
('balsamic vinegar', 'dressings'),
('vinegar', 'dressings'),
('red wine vinegar', 'dressings'),
('rice wine vinegar', 'dressings'),
('white wine vinegar', 'dressings'),
('ranch dressing', 'dressings'),
('italian dressing', 'dressings'),
('sherry vinegar', 'dressings'),
('distilled white vinegar', 'dressings'),
('white balsamic vinegar', 'dressings'),
('sweet chilli sauce', 'dressings'),
('champagne vinegar', 'dressings'),
('vinaigrette dressing', 'dressings'),
('balsamic vinaigrette', 'dressings'),
('seasoned rice vinegar', 'dressings'),
('blue cheese dressing', 'dressings'),
('caesar dressing', 'dressings'),
('thousand island', 'dressings'),
('malt vinegar', 'dressings'),
('black vinegar', 'dressings'),
('canola mayonnaise', 'dressings'),
('raspberry vinegar', 'dressings'),
('japanese mayonnaise', 'dressings'),
('tarragon vinegar', 'dressings'),
('greek vinaigrette', 'dressings'),
('sesame dressing', 'dressings'),
('aioli sauce', 'dressings'),
('honey mustard dressing', 'dressings'),
('french dressing', 'dressings'),
('spicy mayo', 'dressings'),
('poppyseed dressing', 'dressings'),
('catalina dressing', 'dressings'),
('verjuice', 'dressings'),
('cane vinegar', 'dressings'),
('raspberry vinaigrette', 'dressings'),
('red wine vinaigrette', 'dressings'),
('russian dressing', 'dressings'),
('avocado oil mayonnaise', 'dressings'),
('buttermilk ranch dressing', 'dressings'),
('mustard-mayonnaise blend', 'dressings'),
('sushi vinegar', 'dressings'),
('champagne vinaigrette', 'dressings'),
('sun-dried tomato vinaigrette', 'dressings'),
('creamy balsamic dressing', 'dressings'),
('coconut vinegar', 'dressings'),
('garlic mayonnaise', 'dressings'),
('ume plum vinegar', 'dressings'),
('brown rice vinegar', 'dressings'),
('spicy ranch dressing', 'dressings'),
('cilantro dressing', 'dressings'),
('creamy dressing', 'dressings'),
('fig balsamic', 'dressings'),
('green goddess dressing', 'dressings'),
('chipotle aioli', 'dressings'),
('spiced vinegar', 'dressings'),
('lime vinaigrette', 'dressings'),
('onion salad dressing', 'dressings'),
('miso dressing', 'dressings'),
('white balsamic vinaigrette', 'dressings'),
('chardonnay vinegar', 'dressings'),
('prepared coleslaw dressing', 'dressings'),
('honey vinegar', 'dressings'),
('lemon vinegar', 'dressings'),
('tandoori mayonnaise', 'dressings'),
('chilli vinegar', 'dressings'),
('chilli-lime dressing', 'dressings'),
('moscatel vinegar', 'dressings'),
('pomegranate vinegar', 'dressings'),
('vinegar powder', 'dressings'),
('mango vinaigrette', 'dressings'),
('avocado-lime dressing', 'dressings'),
('mustard aioli', 'dressings'),
('caramelised onion dressing', 'dressings'),
('soy sauce', 'condiments'),
('dijon mustard', 'condiments'),
('worcestershire', 'condiments'),
('hot sauce', 'condiments'),
('ketchup', 'condiments'),
('mustard', 'condiments'),
('fish sauce', 'condiments'),
('bbq sauce', 'condiments'),
('sriracha', 'condiments'),
('wholegrain mustard', 'condiments'),
('tamari', 'condiments'),
('oyster sauce', 'condiments'),
('chilli sauce', 'condiments'),
('ginger-garlic paste', 'condiments'),
('brown mustard', 'condiments'),
('teriyaki sauce', 'condiments'),
('wing sauce', 'condiments'),
('prepared horseradish', 'condiments'),
('ginger paste', 'condiments'),
('dark soy sauce', 'condiments'),
('coconut aminos', 'condiments'),
('chilli paste', 'condiments'),
('harissa', 'condiments'),
('chilli-garlic sauce', 'condiments'),
('tamarind paste', 'condiments'),
('pomegranate molasses', 'condiments'),
('gochujang', 'condiments'),
('wasabi', 'condiments'),
('mango chutney', 'condiments'),
('honey mustard', 'condiments'),
('sambal oelek', 'condiments'),
('english mustard', 'condiments'),
('preserved lemon', 'condiments'),
('kecap manis', 'condiments'),
('chutney', 'condiments'),
('shrimp paste', 'condiments'),
('picante sauce', 'condiments'),
('thai sweet chilli sauce', 'condiments'),
('sweet and sour sauce', 'condiments'),
('liquid aminos', 'condiments'),
('chilli-garlic paste', 'condiments'),
('green chutney', 'condiments'),
('tartar sauce', 'condiments'),
('hot pepper jelly', 'condiments'),
('ponzu', 'condiments'),
('sambal', 'condiments'),
('mexican hot sauce', 'condiments'),
('bonito flakes', 'condiments'),
('green chilli sauce', 'condiments'),
('red pepper jelly', 'condiments'),
('crispy onions', 'condiments'),
('thai chilli paste', 'condiments'),
('peri peri', 'condiments'),
('green chilli paste', 'condiments'),
('mint jelly', 'condiments'),
('pepper paste', 'condiments'),
('horseradish mustard', 'condiments'),
('aji amarillo', 'condiments'),
('mustard paste', 'condiments'),
('ginger chilli paste', 'condiments'),
('tamarind chutney', 'condiments'),
('onion marmalade', 'condiments'),
('giardiniera', 'condiments'),
('yuzu juice', 'condiments'),
('chermoula', 'condiments'),
('hp sauce', 'condiments'),
('tonkatsu sauce', 'condiments'),
('duck sauce', 'condiments'),
('doubanjiang', 'condiments'),
('chilli crisp', 'condiments'),
('black soy sauce', 'condiments'),
('doenjang', 'condiments'),
('korean bbq sauce', 'condiments'),
('maggi sauce', 'condiments'),
('chinese mustard', 'condiments'),
('lime pickle', 'condiments'),
('karashi', 'condiments'),
('chamoy', 'condiments'),
('mushroom soy sauce', 'condiments'),
('taucheo', 'condiments'),
('german mustard', 'condiments'),
('yuzu kosho', 'condiments'),
('banana ketchup', 'condiments'),
('remoulade', 'condiments'),
('hot bean paste', 'condiments'),
('patis', 'condiments'),
('pickapeppa sauce', 'condiments'),
('eel sauce', 'condiments'),
('guk ganjang', 'condiments'),
('salsa lizano', 'condiments'),
('white bbq sauce', 'condiments'),
('grape must', 'condiments'),
('shrimp sauce', 'condiments'),
('shrimp powder', 'condiments'),
('chilli puree', 'condiments'),
('green harissa', 'condiments'),
('sweet soybean paste', 'condiments'),
('szechuan sauce', 'condiments'),
('hendersons relish', 'condiments'),
('korean fish sauce', 'condiments'),
('canned tomato', 'cannedFood'),
('capers', 'cannedFood'),
('green olives', 'cannedFood'),
('canned chickpea', 'cannedFood'),
('black olives', 'cannedFood'),
('canned black beans', 'cannedFood'),
('canned pumpkin', 'cannedFood'),
('kalamata olives', 'cannedFood'),
('canned tuna', 'cannedFood'),
('pickle', 'cannedFood'),
('canned pineapple', 'cannedFood'),
('chipotle in adobo', 'cannedFood'),
('roasted red peppers', 'cannedFood'),
('canned anchovy', 'cannedFood'),
('maraschino cherry', 'cannedFood'),
('tomatoes with green chiles', 'cannedFood'),
('canned artichoke', 'cannedFood'),
('canned corn', 'cannedFood'),
('canned whole tomato', 'cannedFood'),
('canned kidney beans', 'cannedFood'),
('canned pie filling', 'cannedFood'),
('refried beans', 'cannedFood'),
('canned cannellini beans', 'cannedFood'),
('sweet pickle relish', 'cannedFood'),
('sauerkraut', 'cannedFood'),
('creamed corn', 'cannedFood'),
('corned beef', 'cannedFood'),
('canned beans', 'cannedFood'),
('pickled jalapenos', 'cannedFood'),
('diced green chiles', 'cannedFood'),
('canned pinto beans', 'cannedFood'),
('sun-dried tomatoes in oil', 'cannedFood'),
('canned mandarin oranges', 'cannedFood'),
('kimchi', 'cannedFood'),
('chilli beans', 'cannedFood'),
('canned crab', 'cannedFood'),
('bamboo shoot', 'cannedFood'),
('baked beans', 'cannedFood'),
('canned mushroom', 'cannedFood'),
('canned salmon', 'cannedFood'),
('pickling juice', 'cannedFood'),
('dill pickle relish', 'cannedFood'),
('canned clam', 'cannedFood'),
('canned water chestnut', 'cannedFood'),
('canned peaches', 'cannedFood'),
('canned black-eyed peas', 'cannedFood'),
('pickled ginger', 'cannedFood'),
('canned whole green chiles', 'cannedFood'),
('canned apple', 'cannedFood'),
('canned green beans', 'cannedFood'),
('spam', 'cannedFood'),
('hearts of palm', 'cannedFood'),
('chilli with beans', 'cannedFood'),
('pickled onions', 'cannedFood'),
('canned lentils', 'cannedFood'),
('fruit cocktail', 'cannedFood'),
('canned peas', 'cannedFood'),
('pickled red onion', 'cannedFood'),
('pimiento-stuffed green olives', 'cannedFood'),
('canned pork', 'cannedFood'),
('pickled beets', 'cannedFood'),
('canned cherry tomato', 'cannedFood'),
('bread & butter pickles', 'cannedFood'),
('canned apricot', 'cannedFood'),
('canned sweet potato', 'cannedFood'),
('canned sour cherry', 'cannedFood'),
('peppadew pepper', 'cannedFood'),
('canned pear', 'cannedFood'),
('pork and beans', 'cannedFood'),
('onion paste', 'cannedFood'),
('canned baby corn', 'cannedFood'),
('pickled vegetables', 'cannedFood'),
('mexican-style corn', 'cannedFood'),
('pumpkin pie filling', 'cannedFood'),
('fire-roasted green chiles', 'cannedFood'),
('chilli without beans', 'cannedFood'),
('banana pepper rings', 'cannedFood'),
('ranch-style beans', 'cannedFood'),
('canned chicken breast', 'cannedFood'),
('canned carrot', 'cannedFood'),
('canned cherry', 'cannedFood'),
('canned mixed beans', 'cannedFood'),
('canned sardines', 'cannedFood'),
('canned lychee', 'cannedFood'),
('ginger in syrup', 'cannedFood'),
('taggiasca olives', 'cannedFood'),
('canned jackfruit', 'cannedFood'),
('tomato relish', 'cannedFood'),
('pickled hot pepper', 'cannedFood'),
('canned potato', 'cannedFood'),
('pickled pepper', 'cannedFood'),
('cranberry relish', 'cannedFood'),
('canned asparagus', 'cannedFood'),
('red pepper relish', 'cannedFood'),
('canned fava beans', 'cannedFood'),
('canned peas and carrots', 'cannedFood'),
('corn relish', 'cannedFood'),
('florina peppers', 'cannedFood'),
('pickled cherry peppers', 'cannedFood'),
('canned yam', 'cannedFood'),
('tomato paste', 'sauces'),
('peanut butter', 'sauces'),
('tomato sauce', 'sauces'),
('salsa', 'sauces'),
('tahini', 'sauces'),
('pesto', 'sauces'),
('pasta sauce', 'sauces'),
('marinara sauce', 'sauces'),
('hoisin sauce', 'sauces'),
('pico de gallo', 'sauces'),
('enchilada sauce', 'sauces'),
('stewed tomatoes', 'sauces'),
('guacamole', 'sauces'),
('hummus', 'sauces'),
('salsa verde', 'sauces'),
('fire-roasted tomato', 'sauces'),
('alfredo sauce', 'sauces'),
('balsamic glaze', 'sauces'),
('anchovy paste', 'sauces'),
('steak sauce', 'sauces'),
('chunky peanut butter', 'sauces'),
('tzatziki', 'sauces'),
('beef gravy', 'sauces'),
('taco sauce', 'sauces'),
('sun-dried tomato pesto', 'sauces'),
('green enchilada sauce', 'sauces'),
('cheese dip', 'sauces'),
('béchamel sauce', 'sauces'),
('horseradish sauce', 'sauces'),
('plum sauce', 'sauces'),
('garlic butter', 'sauces'),
('hollandaise sauce', 'sauces'),
('cocktail sauce', 'sauces'),
('tapenade', 'sauces'),
('black bean sauce', 'sauces'),
('pimento cheese spread', 'sauces'),
('stir-fry sauce', 'sauces'),
('turkey gravy', 'sauces'),
('chicken gravy', 'sauces'),
('thai peanut sauce', 'sauces'),
('sloppy joe sauce', 'sauces'),
('demi-glace', 'sauces'),
('sofrito', 'sauces'),
('mustard sauce', 'sauces'),
('sun-dried tomato paste', 'sauces'),
('french onion dip', 'sauces'),
('chimichurri sauce', 'sauces'),
('herb butter', 'sauces'),
('bolognese sauce', 'sauces'),
('curry sauce', 'sauces'),
('liver spread', 'sauces'),
('browning sauce', 'sauces'),
('schezwan sauce', 'sauces'),
('pork gravy', 'sauces'),
('country gravy', 'sauces'),
('orange sauce', 'sauces'),
('pineapple salsa', 'sauces'),
('artichoke dip', 'sauces'),
('mushroom gravy', 'sauces'),
('chicken demi-glace', 'sauces'),
('mango salsa', 'sauces'),
('olive paste', 'sauces'),
('spinach dip', 'sauces'),
('japanese curry', 'sauces'),
('black truffle butter', 'sauces'),
('black sesame paste', 'sauces'),
('roasted red pepper hummus', 'sauces'),
('whipped cream cheese spread', 'sauces'),
('bacon jam', 'sauces'),
('tikka masala sauce', 'sauces'),
('vodka sauce', 'sauces'),
('green taco sauce', 'sauces'),
('kung pao sauce', 'sauces'),
('sausage gravy', 'sauces'),
('cheese spread', 'sauces'),
('corn salsa', 'sauces'),
('mole paste', 'sauces'),
('onion gravy', 'sauces'),
('pad thai sauce', 'sauces'),
('sesame sauce', 'sauces'),
('butter chicken sauce', 'sauces'),
('deviled ham spread', 'sauces'),
('garlic pasta sauce', 'sauces'),
('garlic spread', 'sauces'),
('green olive tapenade', 'sauces'),
('black pepper sauce', 'sauces'),
('char siu sauce', 'sauces'),
('schezwan chutney', 'sauces'),
('thai red curry sauce', 'sauces'),
('kale pesto', 'sauces'),
('tarama', 'sauces'),
('ssamjang', 'sauces'),
('white pizza sauce', 'sauces'),
('white truffle butter', 'sauces'),
('mango sauce', 'sauces'),
('salsa con queso dip', 'sauces'),
('yum yum sauce', 'sauces'),
('arugula pesto', 'sauces'),
('mango lime sauce', 'sauces'),
('mole sauce', 'sauces'),
('chicken broth', 'soups'),
('vegetable broth', 'soups'),
('chicken stock', 'soups'),
('beef broth', 'soups'),
('beef stock', 'soups'),
('cream of mushroom', 'soups'),
('bouillon cube', 'soups'),
('cream of chicken', 'soups'),
('onion soup mix', 'soups'),
('tomato soup', 'soups'),
('fish stock', 'soups'),
('soup base', 'soups'),
('cream of celery', 'soups'),
('clam juice', 'soups'),
('cheese soup', 'soups'),
('dashi', 'soups'),
('bone broth', 'soups'),
('onion soup', 'soups'),
('veal stock', 'soups'),
('chicken bone broth', 'soups'),
('turkey stock', 'soups'),
('lamb stock', 'soups'),
('turkey broth', 'soups'),
('beef consommé', 'soups'),
('cream of potato', 'soups'),
('stock paste', 'soups'),
('golden mushroom soup', 'soups'),
('seafood stock', 'soups'),
('chicken soup', 'soups'),
('turkey drippings', 'soups'),
('mushroom broth', 'soups'),
('chicken noodle soup', 'soups'),
('vegetable soup mix', 'soups'),
('vegetable soup', 'soups'),
('ramen noodle soup', 'soups'),
('nacho cheese soup', 'soups'),
('shrimp stock', 'soups'),
('beef dripping', 'soups'),
('lobster stock', 'soups'),
('pork stock', 'soups'),
('cream of broccoli', 'soups'),
('chicken rice soup', 'soups'),
('beefy onion soup mix', 'soups'),
('chicken stock paste', 'soups'),
('butternut squash soup', 'soups'),
('clam broth', 'soups'),
('miso soup', 'soups'),
('broccoli-cheese soup', 'soups'),
('duck stock', 'soups'),
('vegan chicken broth', 'soups'),
('ham stock', 'soups'),
('cream of asparagus', 'soups'),
('new england clam chowder', 'soups'),
('beefy mushroom soup', 'soups'),
('pork broth', 'soups'),
('cream of shrimp soup', 'soups'),
('bean soup mix', 'soups'),
('black bean soup', 'soups'),
('chicken consommé', 'soups'),
('cream of bacon', 'soups'),
('lentil soup', 'soups'),
('veal broth', 'soups'),
('vegetable beef soup', 'soups'),
('chicken soup mix', 'soups'),
('roasted garlic chicken broth', 'soups'),
('lobster bisque', 'soups'),
('bean with bacon soup', 'soups'),
('clam chowder', 'soups'),
('condensed chicken gumbo soup', 'soups'),
('thai ginger broth', 'soups'),
('tortilla soup base', 'soups'),
('anchovy stock', 'soups'),
('chicken drippings', 'soups'),
('chicken corn chowder', 'soups'),
('cream of chicken soup mix', 'soups'),
('thai chicken broth', 'soups'),
('turkey bone broth', 'soups'),
('lamb broth', 'soups'),
('minestrone', 'soups'),
('pork & beans', 'soups'),
('tomato bisque', 'soups'),
('venison stock', 'soups'),
('beef stock paste', 'soups'),
('bovril', 'soups'),
('sun-dried tomato bisque mix', 'soups'),
('ham-flavoured concentrate', 'soups'),
('noodle soup mix', 'soups'),
('oxtail soup', 'soups'),
('potato soup mix', 'soups'),
('callaloo', 'soups'),
('split pea soup', 'soups'),
('chicken and mushroom soup', 'soups'),
('chilli beef soup', 'soups'),
('corn chowder', 'soups'),
('cream of cauliflower', 'soups'),
('dashida', 'soups'),
('green pea soup', 'soups'),
('pho broth', 'soups'),
('cocoa', 'desserts'),
('dark chocolate', 'desserts'),
('dark cocoa', 'desserts'),
('chocolate', 'desserts'),
('marshmallow', 'desserts'),
('applesauce', 'desserts'),
('gelatin', 'desserts'),
('white chocolate', 'desserts'),
('graham cracker', 'desserts'),
('graham cracker crumbs', 'desserts'),
('oreo', 'desserts'),
('instant pudding', 'desserts'),
('chocolate hazelnut spread', 'desserts'),
('chocolate candy', 'desserts'),
('dutch-process cocoa', 'desserts'),
('raspberry jam', 'desserts'),
('biscuits', 'desserts'),
('apricot jam', 'desserts'),
('caramel sauce', 'desserts'),
('candy coating', 'desserts'),
('raw cacao powder', 'desserts'),
('strawberry jam', 'desserts'),
('marshmallow creme', 'desserts'),
('candy', 'desserts'),
('baking chocolate', 'desserts'),
('jam', 'desserts'),
('wafer', 'desserts'),
('orange marmalade', 'desserts'),
('cookies', 'desserts'),
('jello', 'desserts'),
('cranberry sauce', 'desserts'),
('chocolate pudding', 'desserts'),
('peanut butter cups', 'desserts'),
('candy cane', 'desserts'),
('ginger snaps', 'desserts'),
('cacao nibs', 'desserts'),
('lady fingers', 'desserts'),
('fudge sauce', 'desserts'),
('chocolate chip cookies', 'desserts'),
('chocolate cookies', 'desserts'),
('apple butter', 'desserts'),
('peppermint candy', 'desserts'),
('cinnamon roll', 'desserts'),
('candied cherry', 'desserts'),
('caramel candies', 'desserts'),
('butter cookies', 'desserts'),
('currant jelly', 'desserts'),
('candied ginger', 'desserts'),
('angel food cake', 'desserts'),
('couverture chocolate', 'desserts'),
('peach preserves', 'desserts'),
('candied peel', 'desserts'),
('cherry jam', 'desserts'),
('dark couverture chocolate', 'desserts'),
('white baking chocolate', 'desserts'),
('chocolate wafer', 'desserts'),
('grape jelly', 'desserts'),
('instant lemon pudding', 'desserts'),
('waffles', 'desserts'),
('agar agar', 'desserts'),
('fig jam', 'desserts'),
('candied fruit', 'desserts'),
('cookie butter', 'desserts'),
('butterscotch', 'desserts'),
('apple jelly', 'desserts'),
('almond cookies', 'desserts'),
('gummies', 'desserts'),
('candy corn', 'desserts'),
('blueberry jam', 'desserts'),
('blackberry preserves', 'desserts'),
('ice-cream cone', 'desserts'),
('egg candies', 'desserts'),
('marmalade', 'desserts'),
('sugar cookies', 'desserts'),
('strawberry puree', 'desserts'),
('chocolate powder', 'desserts'),
('licorice', 'desserts'),
('pineapple jam', 'desserts'),
('chocolate-covered espresso bean', 'desserts'),
('banana pudding', 'desserts'),
('sponge cake', 'desserts'),
('sorbet', 'desserts'),
('mexican chocolate', 'desserts'),
('plum jam', 'desserts'),
('white couverture', 'desserts'),
('cinnamon candy', 'desserts'),
('peanut-butter sandwich cookies', 'desserts'),
('white chocolate pudding', 'desserts'),
('pumpkin butter', 'desserts'),
('chocolate peanut butter', 'desserts'),
('guava paste', 'desserts'),
('butterscotch pudding mix', 'desserts'),
('chocolate spread', 'desserts'),
('fudge', 'desserts'),
('strawberry sauce', 'desserts'),
('doughnut', 'desserts'),
('hershey kisses', 'desserts'),
('biscotti', 'desserts'),
('peppermint patties', 'desserts'),
('cheesecake instant pudding', 'desserts'),
('white wine', 'alcohol'),
('red wine', 'alcohol'),
('whisky', 'alcohol'),
('rum', 'alcohol'),
('vodka', 'alcohol'),
('beer', 'alcohol'),
('orange liqueur', 'alcohol'),
('cider', 'alcohol'),
('tequila', 'alcohol'),
('sherry', 'alcohol'),
('gin', 'alcohol'),
('brandy', 'alcohol'),
('bitters', 'alcohol'),
('mirin', 'alcohol'),
('white rum', 'alcohol'),
('coffee liqueur', 'alcohol'),
('champagne', 'alcohol'),
('vermouth', 'alcohol'),
('irish cream', 'alcohol'),
('amaretto', 'alcohol'),
('marsala wine', 'alcohol'),
('cognac', 'alcohol'),
('sparkling wine', 'alcohol'),
('sake', 'alcohol'),
('shaoxing wine', 'alcohol'),
('rice wine', 'alcohol'),
('dry vermouth', 'alcohol'),
('coconut rum', 'alcohol'),
('liqueur', 'alcohol'),
('curacao', 'alcohol'),
('dessert wine', 'alcohol'),
('port wine', 'alcohol'),
('kirsch', 'alcohol'),
('peach schnapps', 'alcohol'),
('amarula cream', 'alcohol'),
('white cooking wine', 'alcohol'),
('apple brandy', 'alcohol'),
('rose wine', 'alcohol'),
('anise liqueur', 'alcohol'),
('herbal liqueur', 'alcohol'),
('limoncello', 'alcohol'),
('elderflower liqueur', 'alcohol'),
('hazelnut liqueur', 'alcohol'),
('raspberry liqueur', 'alcohol'),
('melon liqueur', 'alcohol'),
('peach liqueur', 'alcohol'),
('banana liqueur', 'alcohol'),
('creme de cacao', 'alcohol'),
('schnapps', 'alcohol'),
('absinthe', 'alcohol'),
('madeira wine', 'alcohol'),
('aperol', 'alcohol'),
('vanilla vodka', 'alcohol'),
('cinnamon alcohol', 'alcohol'),
('creme de menthe', 'alcohol'),
('apricot brandy', 'alcohol'),
('cachaça', 'alcohol'),
('chocolate liqueur', 'alcohol'),
('elderflower cordial', 'alcohol'),
('bénédictine', 'alcohol'),
('ginger liqueur', 'alcohol'),
('creme de cassis', 'alcohol'),
('sloe gin', 'alcohol'),
('maraschino', 'alcohol'),
('red cooking wine', 'alcohol'),
('bloody mary mix', 'alcohol'),
('cream sherry', 'alcohol'),
('gold rum', 'alcohol'),
('sparkling rosé', 'alcohol'),
('drambuie', 'alcohol'),
('grappa', 'alcohol'),
('lime cordial', 'alcohol'),
('strawberry liqueur', 'alcohol'),
('galliano', 'alcohol'),
('mezcal', 'alcohol'),
('ginger wine', 'alcohol'),
('peppermint liqueur', 'alcohol'),
('white port', 'alcohol'),
('advocaat', 'alcohol'),
('piña colada mix', 'alcohol'),
('pumpkin ale', 'alcohol'),
('daiquiri mix', 'alcohol'),
('blackberry schnapps', 'alcohol'),
('coconut liqueur', 'alcohol'),
('rumchata liqueur', 'alcohol'),
('blackberry brandy', 'alcohol'),
('chocolate bitters', 'alcohol'),
('vanilla liqueur', 'alcohol'),
('sangria', 'alcohol'),
('moonshine', 'alcohol'),
('pisco', 'alcohol'),
('plum wine', 'alcohol'),
('grapefruit bitters', 'alcohol'),
('peach brandy', 'alcohol'),
('white chocolate liqueur', 'alcohol'),
('apple liqueur', 'alcohol'),
('pear brandy', 'alcohol'),
('sauternes', 'alcohol'),
('rhum agricole', 'alcohol'),
('apple vodka', 'alcohol'),
('orange juice', 'beverages'),
('coffee', 'beverages'),
('club soda', 'beverages'),
('espresso', 'beverages'),
('pineapple juice', 'beverages'),
('apple juice', 'beverages'),
('tea', 'beverages'),
('cranberry juice', 'beverages'),
('tomato juice', 'beverages'),
('coconut water', 'beverages'),
('pomegranate juice', 'beverages'),
('matcha powder', 'beverages'),
('grapefruit juice', 'beverages'),
('coke', 'beverages'),
('lemonade', 'beverages'),
('ginger ale', 'beverages'),
('eggnog', 'beverages'),
('ginger beer', 'beverages'),
('orange juice concentrate', 'beverages'),
('lemon lime soda', 'beverages'),
('sprite', 'beverages'),
('cream of coconut', 'beverages'),
('green tea', 'beverages'),
('lemonade concentrate', 'beverages'),
('root beer', 'beverages'),
('chai tea', 'beverages'),
('drinking chocolate', 'beverages'),
('tonic water', 'beverages'),
('malted milk powder', 'beverages'),
('cherry juice', 'beverages'),
('sour mix', 'beverages'),
('mango juice', 'beverages'),
('hibiscus', 'beverages'),
('tea leaves', 'beverages'),
('grape juice', 'beverages'),
('limeade concentrate', 'beverages'),
('carrot juice', 'beverages'),
('dr pepper', 'beverages'),
('white grape juice', 'beverages'),
('fruit juice', 'beverages'),
('watermelon juice', 'beverages'),
('tangerine juice', 'beverages'),
('iced tea', 'beverages'),
('kombucha', 'beverages'),
('passion-fruit juice', 'beverages'),
('apricot juice', 'beverages'),
('orange soda', 'beverages'),
('peach juice', 'beverages'),
('beet juice', 'beverages'),
('margarita mix', 'beverages'),
('kool aid', 'beverages'),
('energy drink', 'beverages'),
('chamomile tea', 'beverages'),
('pear juice', 'beverages'),
('rooibos tea', 'beverages'),
('cream soda', 'beverages'),
('mountain dew', 'beverages'),
('tamarind water', 'beverages'),
('tamarind juice', 'beverages'),
('grapefruit soda', 'beverages'),
('lime soda', 'beverages'),
('raspberry juice', 'beverages'),
('clamato', 'beverages'),
('guava juice', 'beverages'),
('jasmine tea', 'beverages'),
('iced coffee concentrate', 'beverages'),
('strawberry juice', 'beverages'),
('green tea leaves', 'beverages'),
('rose syrup', 'beverages'),
('v8 juice', 'beverages'),
('blueberry juice', 'beverages'),
('beetroot juice', 'beverages'),
('lemonade mix', 'beverages'),
('thai tea', 'beverages'),
('pineapple juice concentrate', 'beverages'),
('aloe vera juice', 'beverages'),
('juice blend', 'beverages'),
('prune juice', 'beverages'),
('butterfly pea flower', 'beverages'),
('lapsang souchong', 'beverages'),
('sparkling cider', 'beverages'),
('white tea', 'beverages'),
('berry juice', 'beverages'),
('passion tea', 'beverages'),
('strawberry soda', 'beverages'),
('blackcurrant juice', 'beverages'),
('peppermint tea', 'beverages'),
('lychee juice', 'beverages'),
('herbal tea', 'beverages'),
('banana juice', 'beverages'),
('chicory coffee', 'beverages'),
('cranberry-raspberry juice', 'beverages'),
('raspberry lemonade', 'beverages'),
('decaf coffee', 'beverages'),
('pumpkin spice coffee', 'beverages'),
('cherry soda', 'beverages'),
('lemon water', 'beverages'),
('bitter lemon soda', 'beverages'),
('pepsi', 'beverages'),
('sports drink', 'beverages'),
('coconut extract', 'supplements'),
('rose water', 'supplements'),
('orange extract', 'supplements'),
('rum extract', 'supplements'),
('rock salt', 'supplements'),
('maple extract', 'supplements'),
('chocolate protein powder', 'supplements'),
('collagen', 'supplements'),
('orange blossom water', 'supplements'),
('liquid egg white', 'supplements'),
('peanut butter powder', 'supplements'),
('vegan protein powder', 'supplements'),
('citric acid', 'supplements'),
('maca powder', 'supplements'),
('essence', 'supplements'),
('strawberry extract', 'supplements'),
('spirulina', 'supplements'),
('brewers yeast', 'supplements'),
('coffee extract', 'supplements'),
('butter extract', 'supplements'),
('anise extract', 'supplements'),
('chocolate extract', 'supplements'),
('raspberry extract', 'supplements'),
('lavender oil', 'supplements'),
('cannabis', 'supplements'),
('banana extract', 'supplements'),
('bee pollen', 'supplements'),
('essential oil', 'supplements'),
('caramel extract', 'supplements'),
('root beer extract', 'supplements'),
('vitamin c', 'supplements'),
('corn extract', 'supplements'),
('grapefruit essential oil', 'supplements'),
('greens powder', 'supplements'),
('reishi mushroom', 'supplements'),
('blueberry extract', 'supplements'),
('calcium lactate', 'supplements'),
('daily vitamins', 'supplements'),
('moringa powder', 'supplements'),
('champagne yeast', 'supplements'),
('raspberry powder', 'supplements'),
('sunflower lecithin', 'supplements'),
('thc', 'supplements'),
('banana powder', 'supplements'),
('berry powder', 'supplements'),
('creatine', 'supplements'),
('goji berry powder', 'supplements'),
('magnesium', 'supplements'),
('maqui', 'supplements'),
('rose oil', 'supplements');
